|ERROR|2021-03-13 23:45:32,203|Internal Server Error: /
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\Administrator\Documents\Github\OatFX\OatFX\views.py", line 26, in post
    shobj = shobj(con)
UnboundLocalError: local variable 'shobj' referenced before assignment
|INFO|2021-03-13 23:50:22,365|C:\Users\Administrator\Documents\Github\OatFX\OatFX\views.py changed, reloading.
|ERROR|2021-03-14 00:15:50,353|Internal Server Error: /
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\Administrator\Documents\Github\OatFX\OatFX\views.py", line 39, in post
    return render(request, 'index.html', context)
UnboundLocalError: local variable 'context' referenced before assignment
|INFO|2021-03-14 00:21:46,566|C:\Users\Administrator\Documents\Github\OatFX\OatFX\views.py changed, reloading.
|ERROR|2021-03-14 00:22:57,952|Internal Server Error: /
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\Administrator\Documents\Github\OatFX\OatFX\views.py", line 40, in post
    return render(request, 'index.html', context)
UnboundLocalError: local variable 'context' referenced before assignment
|ERROR|2021-03-14 00:23:30,872|Internal Server Error: /
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\Administrator\Documents\Github\OatFX\OatFX\views.py", line 40, in post
    return render(request, 'index.html', context)
UnboundLocalError: local variable 'context' referenced before assignment
|INFO|2021-03-14 00:26:17,332|C:\Users\Administrator\Documents\Github\OatFX\OatFX\views.py changed, reloading.
|ERROR|2021-03-14 00:27:24,191|Internal Server Error: /
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\Administrator\Documents\Github\OatFX\OatFX\views.py", line 40, in post
    return render(request, 'index.html', context)
UnboundLocalError: local variable 'context' referenced before assignment
|INFO|2021-03-14 00:30:27,604|C:\Users\Administrator\Documents\Github\OatFX\OatFX\views.py changed, reloading.
|WARNING|2021-03-14 00:35:30,719|Not Found: /form
|INFO|2021-03-14 00:36:11,830|C:\Users\Administrator\Documents\Github\OatFX\OatFX\views.py changed, reloading.
|WARNING|2021-03-14 00:38:29,216|Not Found: /livereload.js
|INFO|2021-03-14 00:49:51,783|C:\Users\Administrator\Documents\Github\OatFX\OatFX\views.py changed, reloading.
|ERROR|2021-03-14 00:51:43,615|Internal Server Error: /
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\Administrator\Documents\Github\OatFX\OatFX\views.py", line 33, in post
    return redirect(reverse(''))
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\urls\base.py", line 87, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\urls\resolvers.py", line 685, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for '' not found. '' is not a valid view function or pattern name.
|INFO|2021-03-14 00:54:54,234|C:\Users\Administrator\Documents\Github\OatFX\OatFX\views.py changed, reloading.
|ERROR|2021-03-14 00:56:05,641|Internal Server Error: /
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\Administrator\Documents\Github\OatFX\OatFX\views.py", line 33, in post
    return HttpResponseRedirect('/')
NameError: name 'HttpResponseRedirect' is not defined
|INFO|2021-03-14 00:56:38,019|C:\Users\Administrator\Documents\Github\OatFX\OatFX\views.py changed, reloading.
|ERROR|2021-03-14 00:59:53,365|Server reports an error: {'executed': False, 'error': 'Unauthorized'}.
|ERROR|2021-03-14 00:59:53,366|URL: https://api-demo.fxcm.com:443/trading/get_model?models=ClosedPosition
|ERROR|2021-03-14 00:59:53,367|Headers: {'User-Agent': 'request', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Authorization': 'Bearer T7F1pyQT4so_utJ-ABYb428f4f0130d439c3d02922e4a5d4640a783830fb', 'Content-Type': 'application/x-www-form-urlencoded'}
|ERROR|2021-03-14 00:59:53,368|Params: {'models': ['ClosedPosition']}
|ERROR|2021-03-14 00:59:53,371|Bearer token: None
|ERROR|2021-03-14 00:59:53,372|Connection status: unset
|ERROR|2021-03-14 00:59:53,372|Socket session id: T7F1pyQT4so_utJ-ABYb
|ERROR|2021-03-14 00:59:53,372|Can not parse server answer to json object: {"response":{"executed":false,"error":"Unauthorized"}}.
|ERROR|2021-03-14 00:59:54,027|Internal Server Error: /
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\Administrator\Documents\Github\OatFX\OatFX\views.py", line 29, in post
    con = fx(access_token=token, log_level='error', server='demo', log_file='oatfx.log')
  File "C:\ProgramData\Anaconda3\lib\site-packages\fxcmpy\fxcmpy.py", line 227, in __init__
    self.__collect_positions__()
  File "C:\ProgramData\Anaconda3\lib\site-packages\fxcmpy\fxcmpy.py", line 2299, in __collect_positions__
    data = self.get_closed_positions('list')
  File "C:\ProgramData\Anaconda3\lib\site-packages\fxcmpy\fxcmpy.py", line 393, in get_closed_positions
    closed_pos = data['closed_positions']
KeyError: 'closed_positions'
|WARNING|2021-03-14 01:01:05,786|Not Found: /livereload.js
|INFO|2021-03-14 01:02:02,716|C:\Users\Administrator\Documents\Github\OatFX\OatFX\views.py changed, reloading.
|WARNING|2021-03-14 01:16:23,778|Not Found: /livereload.js
|INFO|2021-03-14 14:45:03,114|C:\Users\Administrator\Documents\Github\OatFX\OatFX\views.py changed, reloading.
|WARNING|2021-03-14 14:51:02,666|Not Found: /livereload.js
|INFO|2021-03-14 15:11:29,384|C:\Users\Administrator\Documents\Github\OatFX\OatFX\ListField.py changed, reloading.
|ERROR|2021-03-15 20:18:30,134|FXCM reject req trading/get_model with status 520 and msg <!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en-US"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en-US"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en-US"> <!--<![endif]-->
<head>
<meta http-equiv="refresh" content="0">

<title>api-demo.fxcm.com | 520: Web server is returning an unknown error</title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/main.css" type="text/css" media="screen,projection" />


</head>
<body>
<div id="cf-wrapper">

    

    <div id="cf-error-details" class="p-0">
        <header class="mx-auto pt-10 lg:pt-6 lg:px-8 w-240 lg:w-full mb-8">
            <h1 class="inline-block sm:block sm:mb-2 font-light text-60 lg:text-4xl text-black-dark leading-tight mr-2">
              
              <span class="cf-error-type">Error</span>
              <span class="cf-error-code">520</span>
            </h1>
            <span class="inline-block sm:block font-mono text-15 lg:text-sm lg:leading-relaxed">Ray ID: 63081683887fc4e8 &bull;</span>
            <span class="inline-block sm:block font-mono text-15 lg:text-sm lg:leading-relaxed">2021-03-15 19:18:33 UTC</span>
            <h2 class="text-gray-600 leading-1.3 text-3xl font-light">Web server is returning an unknown error</h2>
        </header>
        
        <div class="my-8 bg-gradient-gray">
            <div class="w-240 lg:w-full mx-auto">
                <div class="clearfix md:px-8">
                  
<div id="cf-browser-status" class=" relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center">
  <div class="relative mb-10 md:m-0">
    <span class="cf-icon-browser block md:hidden h-20 bg-center bg-no-repeat"></span>
    <span class="cf-icon-ok w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span>
  </div>
  <span class="md:block w-full truncate">You</span>
  <h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3">Browser</h3>
  <span class="leading-1.3 text-2xl text-green-success">Working</span>
</div>

<div id="cf-cloudflare-status" class=" relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center">
  <div class="relative mb-10 md:m-0">
    <span class="cf-icon-cloud block md:hidden h-20 bg-center bg-no-repeat"></span>
    <span class="cf-icon-ok w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span>
  </div>
  <span class="md:block w-full truncate">Lagos</span>
  <h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3">Cloudflare</h3>
  <span class="leading-1.3 text-2xl text-green-success">Working</span>
</div>

<div id="cf-host-status" class="cf-error-source relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center">
  <div class="relative mb-10 md:m-0">
    <span class="cf-icon-server block md:hidden h-20 bg-center bg-no-repeat"></span>
    <span class="cf-icon-error w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span>
  </div>
  <span class="md:block w-full truncate">api-demo.fxcm.com</span>
  <h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3">Host</h3>
  <span class="leading-1.3 text-2xl text-red-error">Error</span>
</div>

                </div>
              
            </div>
        </div>

        <div class="w-240 lg:w-full mx-auto mb-8 lg:px-8">
            <div class="clearfix">
                <div class="w-1/2 md:w-full float-left pr-6 md:pb-10 md:pr-0 leading-relaxed">
                    <h2 class="text-3xl font-normal leading-1.3 mb-4">What happened?</h2>
                    <p>There is an unknown connection issue between Cloudflare and the origin web server. As a result, the web page can not be displayed.</p>
                </div>
              
                <div class="w-1/2 md:w-full float-left leading-relaxed">
                    <h2 class="text-3xl font-normal leading-1.3 mb-4">What can I do?</h2>
                          <h3 class="text-15 font-semibold mb-2">If you are a visitor of this website:</h3>
      <p class="mb-6">Please try again in a few minutes.</p>

      <h3 class="text-15 font-semibold mb-2">If you are the owner of this website:</h3>
      <p><span>There is an issue between Cloudflare's cache and your origin web server. Cloudflare monitors for these errors and automatically investigates the cause. To help support the investigation, you can pull the corresponding error log from your web server and submit it our support team.  Please include the Ray ID (which is at the bottom of this error page).</span> <a rel="noopener noreferrer" href="https://support.cloudflare.com/hc/en-us/articles/200171936-Error-520">Additional troubleshooting resources</a>.</p>
                </div>
            </div>
              
        </div>

        <div class="cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center sm:text-left border-solid border-0 border-t border-gray-300">
  <p class="text-13">
    <span class="cf-footer-item sm:block sm:mb-1">Cloudflare Ray ID: <strong class="font-semibold">63081683887fc4e8</strong></span>
    <span class="cf-footer-separator sm:hidden">&bull;</span>
    <span class="cf-footer-item sm:block sm:mb-1"><span>Your IP</span>: 105.112.38.242</span>
    <span class="cf-footer-separator sm:hidden">&bull;</span>
    <span class="cf-footer-item sm:block sm:mb-1"><span>Performance &amp; security by</span> <a rel="noopener noreferrer" href="https://www.cloudflare.com/5xx-error-landing" id="brand_link" target="_blank">Cloudflare</a></span>
    
  </p>
</div><!-- /.error-footer -->


    </div>
</div>
</body>
</html>

.
|ERROR|2021-03-15 20:18:30,506|Internal Server Error: /
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\Administrator\Documents\Github\OatFX\OatFX\views.py", line 20, in post
    con = fx(access_token=token, log_level='error', server='demo', log_file='oatfx.log')
  File "C:\ProgramData\Anaconda3\lib\site-packages\fxcmpy\fxcmpy.py", line 227, in __init__
    self.__collect_positions__()
  File "C:\ProgramData\Anaconda3\lib\site-packages\fxcmpy\fxcmpy.py", line 2294, in __collect_positions__
    data = self.get_open_positions('list')
  File "C:\ProgramData\Anaconda3\lib\site-packages\fxcmpy\fxcmpy.py", line 372, in get_open_positions
    data = self.get_model(('OpenPosition',))
  File "C:\ProgramData\Anaconda3\lib\site-packages\fxcmpy\fxcmpy.py", line 344, in get_model
    data = self.__handle_request__(method='trading/get_model',
  File "C:\ProgramData\Anaconda3\lib\site-packages\fxcmpy\fxcmpy.py", line 2491, in __handle_request__
    raise ServerError('Request returns status code %s and message "%s"'
fxcmpy.fxcmpy.ServerError: Request returns status code 520 and message "<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en-US"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en-US"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en-US"> <!--<![endif]-->
<head>
<meta http-equiv="refresh" content="0">

<title>api-demo.fxcm.com | 520: Web server is returning an unknown error</title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/main.css" type="text/css" media="screen,projection" />


</head>
<body>
<div id="cf-wrapper">

    

    <div id="cf-error-details" class="p-0">
        <header class="mx-auto pt-10 lg:pt-6 lg:px-8 w-240 lg:w-full mb-8">
            <h1 class="inline-block sm:block sm:mb-2 font-light text-60 lg:text-4xl text-black-dark leading-tight mr-2">
              
              <span class="cf-error-type">Error</span>
              <span class="cf-error-code">520</span>
            </h1>
            <span class="inline-block sm:block font-mono text-15 lg:text-sm lg:leading-relaxed">Ray ID: 63081683887fc4e8 &bull;</span>
            <span class="inline-block sm:block font-mono text-15 lg:text-sm lg:leading-relaxed">2021-03-15 19:18:33 UTC</span>
            <h2 class="text-gray-600 leading-1.3 text-3xl font-light">Web server is returning an unknown error</h2>
        </header>
        
        <div class="my-8 bg-gradient-gray">
            <div class="w-240 lg:w-full mx-auto">
                <div class="clearfix md:px-8">
                  
<div id="cf-browser-status" class=" relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center">
  <div class="relative mb-10 md:m-0">
    <span class="cf-icon-browser block md:hidden h-20 bg-center bg-no-repeat"></span>
    <span class="cf-icon-ok w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span>
  </div>
  <span class="md:block w-full truncate">You</span>
  <h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3">Browser</h3>
  <span class="leading-1.3 text-2xl text-green-success">Working</span>
</div>

<div id="cf-cloudflare-status" class=" relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center">
  <div class="relative mb-10 md:m-0">
    <span class="cf-icon-cloud block md:hidden h-20 bg-center bg-no-repeat"></span>
    <span class="cf-icon-ok w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span>
  </div>
  <span class="md:block w-full truncate">Lagos</span>
  <h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3">Cloudflare</h3>
  <span class="leading-1.3 text-2xl text-green-success">Working</span>
</div>

<div id="cf-host-status" class="cf-error-source relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center">
  <div class="relative mb-10 md:m-0">
    <span class="cf-icon-server block md:hidden h-20 bg-center bg-no-repeat"></span>
    <span class="cf-icon-error w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span>
  </div>
  <span class="md:block w-full truncate">api-demo.fxcm.com</span>
  <h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3">Host</h3>
  <span class="leading-1.3 text-2xl text-red-error">Error</span>
</div>

                </div>
              
            </div>
        </div>

        <div class="w-240 lg:w-full mx-auto mb-8 lg:px-8">
            <div class="clearfix">
                <div class="w-1/2 md:w-full float-left pr-6 md:pb-10 md:pr-0 leading-relaxed">
                    <h2 class="text-3xl font-normal leading-1.3 mb-4">What happened?</h2>
                    <p>There is an unknown connection issue between Cloudflare and the origin web server. As a result, the web page can not be displayed.</p>
                </div>
              
                <div class="w-1/2 md:w-full float-left leading-relaxed">
                    <h2 class="text-3xl font-normal leading-1.3 mb-4">What can I do?</h2>
                          <h3 class="text-15 font-semibold mb-2">If you are a visitor of this website:</h3>
      <p class="mb-6">Please try again in a few minutes.</p>

      <h3 class="text-15 font-semibold mb-2">If you are the owner of this website:</h3>
      <p><span>There is an issue between Cloudflare's cache and your origin web server. Cloudflare monitors for these errors and automatically investigates the cause. To help support the investigation, you can pull the corresponding error log from your web server and submit it our support team.  Please include the Ray ID (which is at the bottom of this error page).</span> <a rel="noopener noreferrer" href="https://support.cloudflare.com/hc/en-us/articles/200171936-Error-520">Additional troubleshooting resources</a>.</p>
                </div>
            </div>
              
        </div>

        <div class="cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center sm:text-left border-solid border-0 border-t border-gray-300">
  <p class="text-13">
    <span class="cf-footer-item sm:block sm:mb-1">Cloudflare Ray ID: <strong class="font-semibold">63081683887fc4e8</strong></span>
    <span class="cf-footer-separator sm:hidden">&bull;</span>
    <span class="cf-footer-item sm:block sm:mb-1"><span>Your IP</span>: 105.112.38.242</span>
    <span class="cf-footer-separator sm:hidden">&bull;</span>
    <span class="cf-footer-item sm:block sm:mb-1"><span>Performance &amp; security by</span> <a rel="noopener noreferrer" href="https://www.cloudflare.com/5xx-error-landing" id="brand_link" target="_blank">Cloudflare</a></span>
    
  </p>
</div><!-- /.error-footer -->


    </div>
</div>
</body>
</html>

"
|ERROR|2021-03-15 20:19:15,443|Socket returns unknown error.
|ERROR|2021-03-15 20:19:15,955|Internal Server Error: /
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\Administrator\Documents\Github\OatFX\OatFX\views.py", line 20, in post
    con = fx(access_token=token, log_level='error', server='demo', log_file='oatfx.log')
  File "C:\ProgramData\Anaconda3\lib\site-packages\fxcmpy\fxcmpy.py", line 218, in __init__
    raise ServerError('Can not connect to FXCM Server.')
fxcmpy.fxcmpy.ServerError: Can not connect to FXCM Server.
|ERROR|2021-03-15 20:19:57,753|Socket returns unknown error.
|ERROR|2021-03-15 20:19:58,758|Internal Server Error: /
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\Administrator\Documents\Github\OatFX\OatFX\views.py", line 20, in post
    con = fx(access_token=token, log_level='error', server='demo', log_file='oatfx.log')
  File "C:\ProgramData\Anaconda3\lib\site-packages\fxcmpy\fxcmpy.py", line 218, in __init__
    raise ServerError('Can not connect to FXCM Server.')
fxcmpy.fxcmpy.ServerError: Can not connect to FXCM Server.
|ERROR|2021-03-15 20:21:46,809|Socket returns unknown error.
|ERROR|2021-03-15 20:21:47,464|Internal Server Error: /
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\Administrator\Documents\Github\OatFX\OatFX\views.py", line 20, in post
    con = fx(access_token=token, log_level='error', server='demo', log_file='oatfx.log')
  File "C:\ProgramData\Anaconda3\lib\site-packages\fxcmpy\fxcmpy.py", line 218, in __init__
    raise ServerError('Can not connect to FXCM Server.')
fxcmpy.fxcmpy.ServerError: Can not connect to FXCM Server.
|ERROR|2021-03-15 20:29:10,804|Socket returns unknown error.
|ERROR|2021-03-15 20:29:11,353|Internal Server Error: /
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\Administrator\Documents\Github\OatFX\OatFX\views.py", line 20, in post
    con = fx(access_token=token, log_level='error', server='demo', log_file='oatfx.log')
  File "C:\ProgramData\Anaconda3\lib\site-packages\fxcmpy\fxcmpy.py", line 218, in __init__
    raise ServerError('Can not connect to FXCM Server.')
fxcmpy.fxcmpy.ServerError: Can not connect to FXCM Server.
|ERROR|2021-03-15 20:30:28,826|Socket returns unknown error.
|ERROR|2021-03-15 20:30:29,578|Internal Server Error: /
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\Administrator\Documents\Github\OatFX\OatFX\views.py", line 20, in post
    con = fx(access_token=token, log_level='error', server='demo', log_file='oatfx.log')
  File "C:\ProgramData\Anaconda3\lib\site-packages\fxcmpy\fxcmpy.py", line 218, in __init__
    raise ServerError('Can not connect to FXCM Server.')
fxcmpy.fxcmpy.ServerError: Can not connect to FXCM Server.
|ERROR|2021-03-15 20:40:23,721|Socket returns unknown error.
|ERROR|2021-03-15 20:40:24,354|Internal Server Error: /
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\Administrator\Documents\Github\OatFX\OatFX\views.py", line 20, in post
    con = fx(access_token=token, log_level='error', server='demo', log_file='oatfx.log')
  File "C:\ProgramData\Anaconda3\lib\site-packages\fxcmpy\fxcmpy.py", line 218, in __init__
    raise ServerError('Can not connect to FXCM Server.')
fxcmpy.fxcmpy.ServerError: Can not connect to FXCM Server.
|INFO|2021-03-15 20:47:26,355|C:\Users\Administrator\Documents\Github\OatFX\OatFX\views.py changed, reloading.
|ERROR|2021-03-15 21:28:45,374|Internal Server Error: /
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "C:\ProgramData\Anaconda3\lib\http\client.py", line 1347, in getresponse
    response.begin()
  File "C:\ProgramData\Anaconda3\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "C:\ProgramData\Anaconda3\lib\http\client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\util\retry.py", line 410, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\packages\six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "C:\ProgramData\Anaconda3\lib\http\client.py", line 1347, in getresponse
    response.begin()
  File "C:\ProgramData\Anaconda3\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "C:\ProgramData\Anaconda3\lib\http\client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\Administrator\Documents\Github\OatFX\OatFX\views.py", line 23, in post
    obj.set_connection(con)
  File "C:\Users\Administrator\Documents\Github\OatFX\OatFX\shared.py", line 24, in set_connection
    self.get_instruments()
  File "C:\Users\Administrator\Documents\Github\OatFX\OatFX\shared.py", line 32, in get_instruments
    data = self.con.get_candles(symbol, period='m1', number=1000)
  File "C:\ProgramData\Anaconda3\lib\site-packages\fxcmpy\fxcmpy.py", line 2184, in get_candles
    data = self.__handle_request__(method='candles/%s/%s'
  File "C:\ProgramData\Anaconda3\lib\site-packages\fxcmpy\fxcmpy.py", line 2478, in __handle_request__
    req = requests.get('%s:443/%s' % (self.trading_url, method),
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
|ERROR|2021-03-15 21:36:37,332|Server reports an error: {'executed': False, 'error': 'Symbol not found or not subscribed.'}.
|ERROR|2021-03-15 21:36:37,333|URL: https://api-demo.fxcm.com:443/candles/9012/m1?num=1000
|ERROR|2021-03-15 21:36:37,334|Headers: {'User-Agent': 'request', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Authorization': 'Bearer NWAAyaOlWBsc_hdSADD3428f4f0130d439c3d02922e4a5d4640a783830fb', 'Content-Type': 'application/x-www-form-urlencoded'}
|ERROR|2021-03-15 21:36:37,334|Params: {'num': 1000}
|ERROR|2021-03-15 21:36:37,335|Bearer token: Bearer NWAAyaOlWBsc_hdSADD3428f4f0130d439c3d02922e4a5d4640a783830fb
|ERROR|2021-03-15 21:36:37,335|Connection status: established
|ERROR|2021-03-15 21:36:37,336|Socket session id: NWAAyaOlWBsc_hdSADD3
|ERROR|2021-03-15 21:36:37,336|Can not parse server answer to json object: {"response":{"executed":false,"error":"Symbol not found or not subscribed."},"instrument_id":0,"period_id":0,"candles":[]}.
|ERROR|2021-03-15 21:36:38,033|Internal Server Error: /
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\Administrator\Documents\Github\OatFX\OatFX\views.py", line 25, in post
    obj.set_connection(con)
  File "C:\Users\Administrator\Documents\Github\OatFX\OatFX\shared.py", line 24, in set_connection
    self.get_instruments()
  File "C:\Users\Administrator\Documents\Github\OatFX\OatFX\shared.py", line 34, in get_instruments
    t0 = data.axes[0].tolist()[len(data.axes[0].tolist())-1]
IndexError: list index out of range
|ERROR|2021-03-15 21:39:22,207|Server reports an error: {'executed': False, 'error': 'Symbol not found or not subscribed.'}.
|ERROR|2021-03-15 21:39:22,211|URL: https://api-demo.fxcm.com:443/candles/9012/m1?num=1000
|ERROR|2021-03-15 21:39:22,212|Headers: {'User-Agent': 'request', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Authorization': 'Bearer NWAAyaOlWBsc_hdSADD3428f4f0130d439c3d02922e4a5d4640a783830fb', 'Content-Type': 'application/x-www-form-urlencoded'}
|ERROR|2021-03-15 21:39:22,212|Params: {'num': 1000}
|ERROR|2021-03-15 21:39:22,212|Bearer token: Bearer NWAAyaOlWBsc_hdSADD3428f4f0130d439c3d02922e4a5d4640a783830fb
|ERROR|2021-03-15 21:39:22,213|Connection status: established
|ERROR|2021-03-15 21:39:22,213|Socket session id: NWAAyaOlWBsc_hdSADD3
|ERROR|2021-03-15 21:39:22,214|Can not parse server answer to json object: {"response":{"executed":false,"error":"Symbol not found or not subscribed."},"instrument_id":0,"period_id":0,"candles":[]}.
|ERROR|2021-03-15 21:39:22,733|Internal Server Error: /
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\Administrator\Documents\Github\OatFX\OatFX\views.py", line 21, in post
    obj.get_instruments()
  File "C:\Users\Administrator\Documents\Github\OatFX\OatFX\shared.py", line 34, in get_instruments
    t0 = data.axes[0].tolist()[len(data.axes[0].tolist())-1]
IndexError: list index out of range
|INFO|2021-03-15 21:41:10,262|C:\Users\Administrator\Documents\Github\OatFX\OatFX\shared.py changed, reloading.
|ERROR|2021-03-15 21:43:31,443|Socket returns unknown error.
|ERROR|2021-03-15 21:43:31,444|Connection aborted, failed to reconnect
|ERROR|2021-03-15 21:43:33,039|Internal Server Error: /
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\Administrator\Documents\Github\OatFX\OatFX\views.py", line 25, in post
    obj.set_connection(con)
  File "C:\Users\Administrator\Documents\Github\OatFX\OatFX\shared.py", line 24, in set_connection
    self.get_instruments()
  File "C:\Users\Administrator\Documents\Github\OatFX\OatFX\shared.py", line 32, in get_instruments
    data = self.con.get_candles(symbol, period='m1', number=1000)
  File "C:\ProgramData\Anaconda3\lib\site-packages\fxcmpy\fxcmpy.py", line 2184, in get_candles
    data = self.__handle_request__(method='candles/%s/%s'
  File "C:\ProgramData\Anaconda3\lib\site-packages\fxcmpy\fxcmpy.py", line 2436, in __handle_request__
    raise IOError('Connection aborted, failed to reconnect')
OSError: Connection aborted, failed to reconnect
|WARNING|2021-03-15 21:44:20,670|Bad Request: /close_connection
|INFO|2021-03-15 21:50:05,254|C:\Users\Administrator\Documents\Github\OatFX\OatFX\shared.py changed, reloading.
|ERROR|2021-03-15 21:55:49,811|Server reports an error: {'executed': False, 'error': 'Symbol not found or not subscribed.'}.
|ERROR|2021-03-15 21:55:49,812|URL: https://api-demo.fxcm.com:443/candles/9012/m1?num=1000
|ERROR|2021-03-15 21:55:49,813|Headers: {'User-Agent': 'request', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Authorization': 'Bearer rdLSWBJZ2LeNMwW7ADKn428f4f0130d439c3d02922e4a5d4640a783830fb', 'Content-Type': 'application/x-www-form-urlencoded'}
|ERROR|2021-03-15 21:55:49,813|Params: {'num': 1000}
|ERROR|2021-03-15 21:55:49,816|Bearer token: Bearer rdLSWBJZ2LeNMwW7ADKn428f4f0130d439c3d02922e4a5d4640a783830fb
|ERROR|2021-03-15 21:55:49,818|Connection status: established
|ERROR|2021-03-15 21:55:49,819|Socket session id: rdLSWBJZ2LeNMwW7ADKn
|ERROR|2021-03-15 21:55:49,819|Can not parse server answer to json object: {"response":{"executed":false,"error":"Symbol not found or not subscribed."},"instrument_id":0,"period_id":0,"candles":[]}.
|ERROR|2021-03-15 21:56:07,300|Error in get_candles: No instrument given!.
|ERROR|2021-03-15 21:56:09,857|Internal Server Error: /
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\Administrator\Documents\Github\OatFX\OatFX\views.py", line 25, in post
    obj.set_connection(con)
  File "C:\Users\Administrator\Documents\Github\OatFX\OatFX\shared.py", line 24, in set_connection
    self.get_instruments()
  File "C:\Users\Administrator\Documents\Github\OatFX\OatFX\shared.py", line 32, in get_instruments
    data = self.con.get_candles(symbol, period='m1', number=1000)
  File "C:\ProgramData\Anaconda3\lib\site-packages\fxcmpy\fxcmpy.py", line 2104, in get_candles
    raise ValueError(msg)
ValueError: Please provide either an instrument or an offer_id
|WARNING|2021-03-15 21:59:29,843|Bad Request: /close_connection
|INFO|2021-03-15 22:02:28,155|C:\Users\Administrator\Documents\Github\OatFX\OatFX\views.py changed, reloading.
|ERROR|2021-03-15 22:07:50,246|Server reports an error: {'executed': False, 'error': 'Symbol not found or not subscribed.'}.
|ERROR|2021-03-15 22:07:50,247|URL: https://api-demo.fxcm.com:443/candles/9012/m1?num=1000
|ERROR|2021-03-15 22:07:50,248|Headers: {'User-Agent': 'request', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Authorization': 'Bearer GCeqMDU9_aAnmAy0ADP1428f4f0130d439c3d02922e4a5d4640a783830fb', 'Content-Type': 'application/x-www-form-urlencoded'}
|ERROR|2021-03-15 22:07:50,249|Params: {'num': 1000}
|ERROR|2021-03-15 22:07:50,250|Bearer token: Bearer GCeqMDU9_aAnmAy0ADP1428f4f0130d439c3d02922e4a5d4640a783830fb
|ERROR|2021-03-15 22:07:50,250|Connection status: established
|ERROR|2021-03-15 22:07:50,251|Socket session id: GCeqMDU9_aAnmAy0ADP1
|ERROR|2021-03-15 22:07:50,251|Can not parse server answer to json object: {"response":{"executed":false,"error":"Symbol not found or not subscribed."},"instrument_id":0,"period_id":0,"candles":[]}.
|ERROR|2021-03-15 22:08:06,525|Server reports an error: {'executed': False, 'error': 'Invalid instrument_id.'}.
|ERROR|2021-03-15 22:08:06,525|URL: https://api-demo.fxcm.com:443/candles/80217/m1?num=1000
|ERROR|2021-03-15 22:08:06,526|Headers: {'User-Agent': 'request', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Authorization': 'Bearer GCeqMDU9_aAnmAy0ADP1428f4f0130d439c3d02922e4a5d4640a783830fb', 'Content-Type': 'application/x-www-form-urlencoded'}
|ERROR|2021-03-15 22:08:06,526|Params: {'num': 1000}
|ERROR|2021-03-15 22:08:06,527|Bearer token: Bearer GCeqMDU9_aAnmAy0ADP1428f4f0130d439c3d02922e4a5d4640a783830fb
|ERROR|2021-03-15 22:08:06,527|Connection status: established
|ERROR|2021-03-15 22:08:06,527|Socket session id: GCeqMDU9_aAnmAy0ADP1
|ERROR|2021-03-15 22:08:06,527|Can not parse server answer to json object: {"response":{"executed":false,"error":"Invalid instrument_id."},"instrument_id":0,"period_id":0,"candles":[]}.
|ERROR|2021-03-15 22:08:07,932|Server reports an error: {'executed': False, 'error': 'Invalid instrument_id.'}.
|ERROR|2021-03-15 22:08:07,935|URL: https://api-demo.fxcm.com:443/candles/80226/m1?num=1000
|ERROR|2021-03-15 22:08:07,936|Headers: {'User-Agent': 'request', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Authorization': 'Bearer GCeqMDU9_aAnmAy0ADP1428f4f0130d439c3d02922e4a5d4640a783830fb', 'Content-Type': 'application/x-www-form-urlencoded'}
|ERROR|2021-03-15 22:08:07,937|Params: {'num': 1000}
|ERROR|2021-03-15 22:08:07,937|Bearer token: Bearer GCeqMDU9_aAnmAy0ADP1428f4f0130d439c3d02922e4a5d4640a783830fb
|ERROR|2021-03-15 22:08:07,938|Connection status: established
|ERROR|2021-03-15 22:08:07,938|Socket session id: GCeqMDU9_aAnmAy0ADP1
|ERROR|2021-03-15 22:08:07,939|Can not parse server answer to json object: {"response":{"executed":false,"error":"Invalid instrument_id."},"instrument_id":0,"period_id":0,"candles":[]}.
|ERROR|2021-03-15 22:08:10,004|Server reports an error: {'executed': False, 'error': 'Invalid instrument_id.'}.
|ERROR|2021-03-15 22:08:10,005|URL: https://api-demo.fxcm.com:443/candles/80231/m1?num=1000
|ERROR|2021-03-15 22:08:10,006|Headers: {'User-Agent': 'request', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Authorization': 'Bearer GCeqMDU9_aAnmAy0ADP1428f4f0130d439c3d02922e4a5d4640a783830fb', 'Content-Type': 'application/x-www-form-urlencoded'}
|ERROR|2021-03-15 22:08:10,007|Params: {'num': 1000}
|ERROR|2021-03-15 22:08:10,007|Bearer token: Bearer GCeqMDU9_aAnmAy0ADP1428f4f0130d439c3d02922e4a5d4640a783830fb
|ERROR|2021-03-15 22:08:10,008|Connection status: established
|ERROR|2021-03-15 22:08:10,008|Socket session id: GCeqMDU9_aAnmAy0ADP1
|ERROR|2021-03-15 22:08:10,008|Can not parse server answer to json object: {"response":{"executed":false,"error":"Invalid instrument_id."},"instrument_id":0,"period_id":0,"candles":[]}.
|ERROR|2021-03-15 22:08:11,236|FXCM Server reports an unknown error: {'executed': False, 'error': ''}.
|ERROR|2021-03-15 22:08:11,236|Can not parse server answer to json object: {"response":{"executed":false,"error":""},"instrument_id":"80235","period_id":"m1","candles":[]}.
|ERROR|2021-03-15 22:08:11,933|Server reports an error: {'executed': False, 'error': 'Invalid instrument_id.'}.
|ERROR|2021-03-15 22:08:11,934|URL: https://api-demo.fxcm.com:443/candles/80240/m1?num=1000
|ERROR|2021-03-15 22:08:11,934|Headers: {'User-Agent': 'request', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Authorization': 'Bearer GCeqMDU9_aAnmAy0ADP1428f4f0130d439c3d02922e4a5d4640a783830fb', 'Content-Type': 'application/x-www-form-urlencoded'}
|ERROR|2021-03-15 22:08:11,934|Params: {'num': 1000}
|ERROR|2021-03-15 22:08:11,935|Bearer token: Bearer GCeqMDU9_aAnmAy0ADP1428f4f0130d439c3d02922e4a5d4640a783830fb
|ERROR|2021-03-15 22:08:11,936|Connection status: established
|ERROR|2021-03-15 22:08:11,936|Socket session id: GCeqMDU9_aAnmAy0ADP1
|ERROR|2021-03-15 22:08:11,937|Can not parse server answer to json object: {"response":{"executed":false,"error":"Invalid instrument_id."},"instrument_id":0,"period_id":0,"candles":[]}.
|ERROR|2021-03-15 22:08:15,689|FXCM Server reports an unknown error: {'executed': False, 'error': ''}.
|ERROR|2021-03-15 22:08:15,690|Can not parse server answer to json object: {"response":{"executed":false,"error":""},"instrument_id":"80255","period_id":"m1","candles":[]}.
|ERROR|2021-03-15 22:08:16,165|Server reports an error: {'executed': False, 'error': 'Invalid instrument_id.'}.
|ERROR|2021-03-15 22:08:16,166|URL: https://api-demo.fxcm.com:443/candles/80259/m1?num=1000
|ERROR|2021-03-15 22:08:16,166|Headers: {'User-Agent': 'request', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Authorization': 'Bearer GCeqMDU9_aAnmAy0ADP1428f4f0130d439c3d02922e4a5d4640a783830fb', 'Content-Type': 'application/x-www-form-urlencoded'}
|ERROR|2021-03-15 22:08:16,167|Params: {'num': 1000}
|ERROR|2021-03-15 22:08:16,167|Bearer token: Bearer GCeqMDU9_aAnmAy0ADP1428f4f0130d439c3d02922e4a5d4640a783830fb
|ERROR|2021-03-15 22:08:16,168|Connection status: established
|ERROR|2021-03-15 22:08:16,168|Socket session id: GCeqMDU9_aAnmAy0ADP1
|ERROR|2021-03-15 22:08:16,168|Can not parse server answer to json object: {"response":{"executed":false,"error":"Invalid instrument_id."},"instrument_id":0,"period_id":0,"candles":[]}.
|ERROR|2021-03-15 22:08:18,174|Server reports an error: {'executed': False, 'error': 'Invalid instrument_id.'}.
|ERROR|2021-03-15 22:08:18,174|URL: https://api-demo.fxcm.com:443/candles/80270/m1?num=1000
|ERROR|2021-03-15 22:08:18,175|Headers: {'User-Agent': 'request', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Authorization': 'Bearer GCeqMDU9_aAnmAy0ADP1428f4f0130d439c3d02922e4a5d4640a783830fb', 'Content-Type': 'application/x-www-form-urlencoded'}
|ERROR|2021-03-15 22:08:18,176|Params: {'num': 1000}
|ERROR|2021-03-15 22:08:18,176|Bearer token: Bearer GCeqMDU9_aAnmAy0ADP1428f4f0130d439c3d02922e4a5d4640a783830fb
|ERROR|2021-03-15 22:08:18,176|Connection status: established
|ERROR|2021-03-15 22:08:18,177|Socket session id: GCeqMDU9_aAnmAy0ADP1
|ERROR|2021-03-15 22:08:18,177|Can not parse server answer to json object: {"response":{"executed":false,"error":"Invalid instrument_id."},"instrument_id":0,"period_id":0,"candles":[]}.
|ERROR|2021-03-15 22:08:18,966|FXCM Server reports an unknown error: {'executed': False, 'error': ''}.
|ERROR|2021-03-15 22:08:18,967|Can not parse server answer to json object: {"response":{"executed":false,"error":""},"instrument_id":"80273","period_id":"m1","candles":[]}.
|ERROR|2021-03-15 22:08:21,218|Server reports an error: {'executed': False, 'error': 'Invalid instrument_id.'}.
|ERROR|2021-03-15 22:08:21,218|URL: https://api-demo.fxcm.com:443/candles/80358/m1?num=1000
|ERROR|2021-03-15 22:08:21,219|Headers: {'User-Agent': 'request', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Authorization': 'Bearer GCeqMDU9_aAnmAy0ADP1428f4f0130d439c3d02922e4a5d4640a783830fb', 'Content-Type': 'application/x-www-form-urlencoded'}
|ERROR|2021-03-15 22:08:21,219|Params: {'num': 1000}
|ERROR|2021-03-15 22:08:21,220|Bearer token: Bearer GCeqMDU9_aAnmAy0ADP1428f4f0130d439c3d02922e4a5d4640a783830fb
|ERROR|2021-03-15 22:08:21,220|Connection status: established
|ERROR|2021-03-15 22:08:21,220|Socket session id: GCeqMDU9_aAnmAy0ADP1
|ERROR|2021-03-15 22:08:21,221|Can not parse server answer to json object: {"response":{"executed":false,"error":"Invalid instrument_id."},"instrument_id":0,"period_id":0,"candles":[]}.
|ERROR|2021-03-15 22:08:24,770|Server reports an error: {'executed': False, 'error': 'Invalid instrument_id.'}.
|ERROR|2021-03-15 22:08:24,771|URL: https://api-demo.fxcm.com:443/candles/80366/m1?num=1000
|ERROR|2021-03-15 22:08:24,771|Headers: {'User-Agent': 'request', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Authorization': 'Bearer GCeqMDU9_aAnmAy0ADP1428f4f0130d439c3d02922e4a5d4640a783830fb', 'Content-Type': 'application/x-www-form-urlencoded'}
|ERROR|2021-03-15 22:08:24,772|Params: {'num': 1000}
|ERROR|2021-03-15 22:08:24,772|Bearer token: Bearer GCeqMDU9_aAnmAy0ADP1428f4f0130d439c3d02922e4a5d4640a783830fb
|ERROR|2021-03-15 22:08:24,773|Connection status: established
|ERROR|2021-03-15 22:08:24,773|Socket session id: GCeqMDU9_aAnmAy0ADP1
|ERROR|2021-03-15 22:08:24,773|Can not parse server answer to json object: {"response":{"executed":false,"error":"Invalid instrument_id."},"instrument_id":0,"period_id":0,"candles":[]}.
|ERROR|2021-03-15 22:08:25,249|Server reports an error: {'executed': False, 'error': 'Invalid instrument_id.'}.
|ERROR|2021-03-15 22:08:25,250|URL: https://api-demo.fxcm.com:443/candles/80378/m1?num=1000
|ERROR|2021-03-15 22:08:25,250|Headers: {'User-Agent': 'request', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Authorization': 'Bearer GCeqMDU9_aAnmAy0ADP1428f4f0130d439c3d02922e4a5d4640a783830fb', 'Content-Type': 'application/x-www-form-urlencoded'}
|ERROR|2021-03-15 22:08:25,250|Params: {'num': 1000}
|ERROR|2021-03-15 22:08:25,251|Bearer token: Bearer GCeqMDU9_aAnmAy0ADP1428f4f0130d439c3d02922e4a5d4640a783830fb
|ERROR|2021-03-15 22:08:25,251|Connection status: established
|ERROR|2021-03-15 22:08:25,251|Socket session id: GCeqMDU9_aAnmAy0ADP1
|ERROR|2021-03-15 22:08:25,252|Can not parse server answer to json object: {"response":{"executed":false,"error":"Invalid instrument_id."},"instrument_id":0,"period_id":0,"candles":[]}.
|ERROR|2021-03-15 22:08:27,983|Server reports an error: {'executed': False, 'error': 'Invalid instrument_id.'}.
|ERROR|2021-03-15 22:08:27,984|URL: https://api-demo.fxcm.com:443/candles/80419/m1?num=1000
|ERROR|2021-03-15 22:08:27,985|Headers: {'User-Agent': 'request', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Authorization': 'Bearer GCeqMDU9_aAnmAy0ADP1428f4f0130d439c3d02922e4a5d4640a783830fb', 'Content-Type': 'application/x-www-form-urlencoded'}
|ERROR|2021-03-15 22:08:27,985|Params: {'num': 1000}
|ERROR|2021-03-15 22:08:27,986|Bearer token: Bearer GCeqMDU9_aAnmAy0ADP1428f4f0130d439c3d02922e4a5d4640a783830fb
|ERROR|2021-03-15 22:08:27,986|Connection status: established
|ERROR|2021-03-15 22:08:27,986|Socket session id: GCeqMDU9_aAnmAy0ADP1
|ERROR|2021-03-15 22:08:27,987|Can not parse server answer to json object: {"response":{"executed":false,"error":"Invalid instrument_id."},"instrument_id":0,"period_id":0,"candles":[]}.
|ERROR|2021-03-15 22:08:31,770|Server reports an error: {'executed': False, 'error': 'Invalid instrument_id.'}.
|ERROR|2021-03-15 22:08:31,772|URL: https://api-demo.fxcm.com:443/candles/80582/m1?num=1000
|ERROR|2021-03-15 22:08:31,773|Headers: {'User-Agent': 'request', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Authorization': 'Bearer GCeqMDU9_aAnmAy0ADP1428f4f0130d439c3d02922e4a5d4640a783830fb', 'Content-Type': 'application/x-www-form-urlencoded'}
|ERROR|2021-03-15 22:08:31,773|Params: {'num': 1000}
|ERROR|2021-03-15 22:08:31,773|Bearer token: Bearer GCeqMDU9_aAnmAy0ADP1428f4f0130d439c3d02922e4a5d4640a783830fb
|ERROR|2021-03-15 22:08:31,774|Connection status: established
|ERROR|2021-03-15 22:08:31,774|Socket session id: GCeqMDU9_aAnmAy0ADP1
|ERROR|2021-03-15 22:08:31,774|Can not parse server answer to json object: {"response":{"executed":false,"error":"Invalid instrument_id."},"instrument_id":0,"period_id":0,"candles":[]}.
|ERROR|2021-03-15 22:08:39,289|Server reports an error: {'executed': False, 'error': 'Unauthorized'}.
|ERROR|2021-03-15 22:08:39,289|URL: https://api-demo.fxcm.com:443/candles/80960/m1?num=1000
|ERROR|2021-03-15 22:08:39,290|Headers: {'User-Agent': 'request', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Authorization': 'Bearer GCeqMDU9_aAnmAy0ADP1428f4f0130d439c3d02922e4a5d4640a783830fb', 'Content-Type': 'application/x-www-form-urlencoded'}
|ERROR|2021-03-15 22:08:39,290|Params: {'num': 1000}
|ERROR|2021-03-15 22:08:39,291|Bearer token: None
|ERROR|2021-03-15 22:08:39,291|Connection status: unset
|ERROR|2021-03-15 22:08:39,291|Socket session id: None
|ERROR|2021-03-15 22:08:39,292|Can not parse server answer to json object: {"response":{"executed":false,"error":"Unauthorized"},"instrument_id":0,"period_id":0,"candles":[]}.
|ERROR|2021-03-15 22:08:39,346|Socket returns unknown error.
|ERROR|2021-03-15 22:08:39,347|Connection aborted, failed to reconnect
|ERROR|2021-03-15 22:08:41,059|Internal Server Error: /
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\Administrator\Documents\Github\OatFX\OatFX\views.py", line 25, in post
    obj.set_connection(con)
  File "C:\Users\Administrator\Documents\Github\OatFX\OatFX\shared.py", line 24, in set_connection
    self.get_instruments()
  File "C:\Users\Administrator\Documents\Github\OatFX\OatFX\shared.py", line 34, in get_instruments
    data = self.con.get_candles(symbol, period='m1', number=1000)
  File "C:\ProgramData\Anaconda3\lib\site-packages\fxcmpy\fxcmpy.py", line 2184, in get_candles
    data = self.__handle_request__(method='candles/%s/%s'
  File "C:\ProgramData\Anaconda3\lib\site-packages\fxcmpy\fxcmpy.py", line 2436, in __handle_request__
    raise IOError('Connection aborted, failed to reconnect')
OSError: Connection aborted, failed to reconnect
|INFO|2021-03-15 22:11:41,183|C:\Users\Administrator\Documents\Github\OatFX\OatFX\shared.py changed, reloading.
|ERROR|2021-03-15 22:19:13,046|Socket returns unknown error.
|ERROR|2021-03-15 22:19:13,670|Internal Server Error: /
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\Administrator\Documents\Github\OatFX\OatFX\views.py", line 24, in post
    con = fx(access_token=token, log_level='error', server='demo', log_file='oatfx.log')
  File "C:\ProgramData\Anaconda3\lib\site-packages\fxcmpy\fxcmpy.py", line 218, in __init__
    raise ServerError('Can not connect to FXCM Server.')
fxcmpy.fxcmpy.ServerError: Can not connect to FXCM Server.
|ERROR|2021-03-15 22:19:26,218|Internal Server Error: /
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\Administrator\Documents\Github\OatFX\OatFX\views.py", line 25, in post
    obj.set_connection(con)
  File "C:\Users\Administrator\Documents\Github\OatFX\OatFX\shared.py", line 257, in set_connection
    self.get_instruments()
  File "C:\Users\Administrator\Documents\Github\OatFX\OatFX\shared.py", line 264, in get_instruments
    while ("" in self.instruments):
AttributeError: 'SharedObjects' object has no attribute 'instruments'
|ERROR|2021-03-15 22:19:26,944|Internal Server Error: /
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\Administrator\Documents\Github\OatFX\OatFX\views.py", line 21, in post
    obj.get_instruments()
  File "C:\Users\Administrator\Documents\Github\OatFX\OatFX\shared.py", line 264, in get_instruments
    while ("" in self.instruments):
AttributeError: 'SharedObjects' object has no attribute 'instruments'
|INFO|2021-03-15 22:27:00,108|C:\Users\Administrator\Documents\Github\OatFX\OatFX\shared.py changed, reloading.
|ERROR|2021-03-15 22:31:41,132|Server reports an error: {'executed': False, 'error': 'Invalid instrument_id.'}.
|ERROR|2021-03-15 22:31:41,133|URL: https://api-demo.fxcm.com:443/candles/80378/m1?num=1000
|ERROR|2021-03-15 22:31:41,134|Headers: {'User-Agent': 'request', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Authorization': 'Bearer cY9SbX-yUmUr9lYRADat428f4f0130d439c3d02922e4a5d4640a783830fb', 'Content-Type': 'application/x-www-form-urlencoded'}
|ERROR|2021-03-15 22:31:41,135|Params: {'num': 1000}
|ERROR|2021-03-15 22:31:41,135|Bearer token: Bearer cY9SbX-yUmUr9lYRADat428f4f0130d439c3d02922e4a5d4640a783830fb
|ERROR|2021-03-15 22:31:41,136|Connection status: established
|ERROR|2021-03-15 22:31:41,137|Socket session id: cY9SbX-yUmUr9lYRADat
|ERROR|2021-03-15 22:31:41,137|Can not parse server answer to json object: {"response":{"executed":false,"error":"Invalid instrument_id."},"instrument_id":0,"period_id":0,"candles":[]}.
|ERROR|2021-03-15 22:33:46,792|Server reports an error: {'executed': False, 'error': 'Invalid instrument_id.'}.
|ERROR|2021-03-15 22:33:46,792|URL: https://api-demo.fxcm.com:443/candles/80378/m1?num=1000
|ERROR|2021-03-15 22:33:46,793|Headers: {'User-Agent': 'request', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Authorization': 'Bearer zQ2d-XOOSfN7R6sZADbi428f4f0130d439c3d02922e4a5d4640a783830fb', 'Content-Type': 'application/x-www-form-urlencoded'}
|ERROR|2021-03-15 22:33:46,793|Params: {'num': 1000}
|ERROR|2021-03-15 22:33:46,793|Bearer token: Bearer zQ2d-XOOSfN7R6sZADbi428f4f0130d439c3d02922e4a5d4640a783830fb
|ERROR|2021-03-15 22:33:46,794|Connection status: established
|ERROR|2021-03-15 22:33:46,794|Socket session id: zQ2d-XOOSfN7R6sZADbi
|ERROR|2021-03-15 22:33:46,794|Can not parse server answer to json object: {"response":{"executed":false,"error":"Invalid instrument_id."},"instrument_id":0,"period_id":0,"candles":[]}.
|INFO|2021-03-15 22:35:40,040|C:\Users\Administrator\Documents\Github\OatFX\OatFX\shared.py changed, reloading.
|ERROR|2021-03-15 22:37:32,569|Server reports an error: {'executed': False, 'error': 'Invalid instrument_id.'}.
|ERROR|2021-03-15 22:37:32,570|URL: https://api-demo.fxcm.com:443/candles/80378/m1?num=1000
|ERROR|2021-03-15 22:37:32,570|Headers: {'User-Agent': 'request', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Authorization': 'Bearer fiqc-jDeRpyirSZPADdP428f4f0130d439c3d02922e4a5d4640a783830fb', 'Content-Type': 'application/x-www-form-urlencoded'}
|ERROR|2021-03-15 22:37:32,571|Params: {'num': 1000}
|ERROR|2021-03-15 22:37:32,571|Bearer token: Bearer fiqc-jDeRpyirSZPADdP428f4f0130d439c3d02922e4a5d4640a783830fb
|ERROR|2021-03-15 22:37:32,571|Connection status: established
|ERROR|2021-03-15 22:37:32,572|Socket session id: fiqc-jDeRpyirSZPADdP
|ERROR|2021-03-15 22:37:32,573|Can not parse server answer to json object: {"response":{"executed":false,"error":"Invalid instrument_id."},"instrument_id":0,"period_id":0,"candles":[]}.
|INFO|2021-03-15 22:57:55,628|C:\Users\Administrator\Documents\Github\OatFX\OatFX\views.py changed, reloading.
|WARNING|2021-03-15 23:26:56,696|Bad Request: /close_connection
|WARNING|2021-03-15 23:27:14,214|Bad Request: /close_connection
|WARNING|2021-03-15 23:27:24,593|Bad Request: /close_connection
|ERROR|2021-03-15 23:27:26,205|Socket returns unknown error.
|ERROR|2021-03-15 23:27:27,206|Internal Server Error: /
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\Administrator\Documents\Github\OatFX\OatFX\views.py", line 24, in post
    con = fx(access_token=token, log_level='error', server='demo', log_file='oatfx.log')
  File "C:\ProgramData\Anaconda3\lib\site-packages\fxcmpy\fxcmpy.py", line 218, in __init__
    raise ServerError('Can not connect to FXCM Server.')
fxcmpy.fxcmpy.ServerError: Can not connect to FXCM Server.
|WARNING|2021-03-15 23:28:02,922|Bad Request: /close_connection
|INFO|2021-03-15 23:30:55,904|C:\Users\Administrator\Documents\Github\OatFX\OatFX\views.py changed, reloading.
|ERROR|2021-03-15 23:41:13,204|Internal Server Error: /close_connection
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Administrator\Documents\Github\OatFX\OatFX\views.py", line 49, in close_connection
    obj.cleardb()
  File "C:\Users\Administrator\Documents\Github\OatFX\OatFX\shared.py", line 247, in cleardb
    name.objects.delete()
AttributeError: 'Manager' object has no attribute 'delete'
|ERROR|2021-03-15 23:41:37,153|Internal Server Error: /close_connection
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Administrator\Documents\Github\OatFX\OatFX\views.py", line 49, in close_connection
    obj.cleardb()
  File "C:\Users\Administrator\Documents\Github\OatFX\OatFX\shared.py", line 247, in cleardb
    name.objects.delete()
AttributeError: 'Manager' object has no attribute 'delete'
|INFO|2021-03-15 23:47:18,079|C:\Users\Administrator\Documents\Github\OatFX\OatFX\shared.py changed, reloading.
|ERROR|2021-03-16 00:07:08,251|Internal Server Error: /
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\Administrator\Documents\Github\OatFX\OatFX\views.py", line 25, in post
    obj.set_connection(con)
  File "C:\Users\Administrator\Documents\Github\OatFX\OatFX\shared.py", line 24, in set_connection
    self.get_instruments()
  File "C:\Users\Administrator\Documents\Github\OatFX\OatFX\shared.py", line 37, in get_instruments
    while ("" in self.instruments):
AttributeError: 'SharedObjects' object has no attribute 'instruments'
|INFO|2021-03-16 00:08:23,236|C:\Users\Administrator\Documents\Github\OatFX\OatFX\shared.py changed, reloading.
|ERROR|2021-03-16 00:09:45,516|Internal Server Error: /close_connection
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Administrator\Documents\Github\OatFX\OatFX\views.py", line 49, in close_connection
    obj.cleardb()
  File "C:\Users\Administrator\Documents\Github\OatFX\OatFX\shared.py", line 76, in cleardb
    name.objects.delete()
AttributeError: 'Manager' object has no attribute 'delete'
|ERROR|2021-03-16 00:10:02,066|Internal Server Error: /close_connection
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Administrator\Documents\Github\OatFX\OatFX\views.py", line 49, in close_connection
    obj.cleardb()
  File "C:\Users\Administrator\Documents\Github\OatFX\OatFX\shared.py", line 76, in cleardb
    name.objects.delete()
AttributeError: 'Manager' object has no attribute 'delete'
|INFO|2021-03-16 00:16:26,291|C:\Users\Administrator\Documents\Github\OatFX\OatFX\views.py changed, reloading.
|ERROR|2021-03-16 00:19:36,876|Internal Server Error: /close_connection
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Administrator\Documents\Github\OatFX\OatFX\views.py", line 49, in close_connection
    obj.cleardb()
  File "C:\Users\Administrator\Documents\Github\OatFX\OatFX\shared.py", line 76, in cleardb
    name.objects.delete()
AttributeError: 'Manager' object has no attribute 'delete'
|INFO|2021-03-16 00:23:07,516|C:\Users\Administrator\Documents\Github\OatFX\OatFX\views.py changed, reloading.
|INFO|2021-03-16 00:28:37,279|C:\Users\Administrator\Documents\Github\OatFX\OatFX\shared.py changed, reloading.
|ERROR|2021-03-16 00:39:05,505|Server reports an error: {'executed': False, 'error': 'Symbol not found or not subscribed.'}.
|ERROR|2021-03-16 00:39:05,505|URL: https://api-demo.fxcm.com:443/candles/9012/m1?num=1000
|ERROR|2021-03-16 00:39:05,506|Headers: {'User-Agent': 'request', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Authorization': 'Bearer Kx7ky1Q7vfx6D46bAEMT428f4f0130d439c3d02922e4a5d4640a783830fb', 'Content-Type': 'application/x-www-form-urlencoded'}
|ERROR|2021-03-16 00:39:05,507|Params: {'num': 1000}
|ERROR|2021-03-16 00:39:05,507|Bearer token: Bearer Kx7ky1Q7vfx6D46bAEMT428f4f0130d439c3d02922e4a5d4640a783830fb
|ERROR|2021-03-16 00:39:05,507|Connection status: established
|ERROR|2021-03-16 00:39:05,508|Socket session id: Kx7ky1Q7vfx6D46bAEMT
|ERROR|2021-03-16 00:39:05,508|Can not parse server answer to json object: {"response":{"executed":false,"error":"Symbol not found or not subscribed."},"instrument_id":0,"period_id":0,"candles":[]}.
|ERROR|2021-03-16 00:39:17,233|Server reports an error: {'executed': False, 'error': 'Invalid instrument_id.'}.
|ERROR|2021-03-16 00:39:17,233|URL: https://api-demo.fxcm.com:443/candles/80217/m1?num=1000
|ERROR|2021-03-16 00:39:17,234|Headers: {'User-Agent': 'request', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Authorization': 'Bearer Kx7ky1Q7vfx6D46bAEMT428f4f0130d439c3d02922e4a5d4640a783830fb', 'Content-Type': 'application/x-www-form-urlencoded'}
|ERROR|2021-03-16 00:39:17,234|Params: {'num': 1000}
|ERROR|2021-03-16 00:39:17,234|Bearer token: Bearer Kx7ky1Q7vfx6D46bAEMT428f4f0130d439c3d02922e4a5d4640a783830fb
|ERROR|2021-03-16 00:39:17,235|Connection status: established
|ERROR|2021-03-16 00:39:17,235|Socket session id: Kx7ky1Q7vfx6D46bAEMT
|ERROR|2021-03-16 00:39:17,235|Can not parse server answer to json object: {"response":{"executed":false,"error":"Invalid instrument_id."},"instrument_id":0,"period_id":0,"candles":[]}.
|ERROR|2021-03-16 00:39:18,237|Server reports an error: {'executed': False, 'error': 'Invalid instrument_id.'}.
|ERROR|2021-03-16 00:39:18,239|URL: https://api-demo.fxcm.com:443/candles/80226/m1?num=1000
|ERROR|2021-03-16 00:39:18,239|Headers: {'User-Agent': 'request', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Authorization': 'Bearer Kx7ky1Q7vfx6D46bAEMT428f4f0130d439c3d02922e4a5d4640a783830fb', 'Content-Type': 'application/x-www-form-urlencoded'}
|ERROR|2021-03-16 00:39:18,240|Params: {'num': 1000}
|ERROR|2021-03-16 00:39:18,240|Bearer token: Bearer Kx7ky1Q7vfx6D46bAEMT428f4f0130d439c3d02922e4a5d4640a783830fb
|ERROR|2021-03-16 00:39:18,241|Connection status: established
|ERROR|2021-03-16 00:39:18,241|Socket session id: Kx7ky1Q7vfx6D46bAEMT
|ERROR|2021-03-16 00:39:18,241|Can not parse server answer to json object: {"response":{"executed":false,"error":"Invalid instrument_id."},"instrument_id":0,"period_id":0,"candles":[]}.
|ERROR|2021-03-16 00:39:19,459|Server reports an error: {'executed': False, 'error': 'Invalid instrument_id.'}.
|ERROR|2021-03-16 00:39:19,459|URL: https://api-demo.fxcm.com:443/candles/80231/m1?num=1000
|ERROR|2021-03-16 00:39:19,459|Headers: {'User-Agent': 'request', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Authorization': 'Bearer Kx7ky1Q7vfx6D46bAEMT428f4f0130d439c3d02922e4a5d4640a783830fb', 'Content-Type': 'application/x-www-form-urlencoded'}
|ERROR|2021-03-16 00:39:19,460|Params: {'num': 1000}
|ERROR|2021-03-16 00:39:19,460|Bearer token: Bearer Kx7ky1Q7vfx6D46bAEMT428f4f0130d439c3d02922e4a5d4640a783830fb
|ERROR|2021-03-16 00:39:19,460|Connection status: established
|ERROR|2021-03-16 00:39:19,461|Socket session id: Kx7ky1Q7vfx6D46bAEMT
|ERROR|2021-03-16 00:39:19,461|Can not parse server answer to json object: {"response":{"executed":false,"error":"Invalid instrument_id."},"instrument_id":0,"period_id":0,"candles":[]}.
|ERROR|2021-03-16 00:39:20,184|FXCM Server reports an unknown error: {'executed': False, 'error': ''}.
|ERROR|2021-03-16 00:39:20,185|Can not parse server answer to json object: {"response":{"executed":false,"error":""},"instrument_id":"80235","period_id":"m1","candles":[]}.
|ERROR|2021-03-16 00:39:20,623|Server reports an error: {'executed': False, 'error': 'Invalid instrument_id.'}.
|ERROR|2021-03-16 00:39:20,624|URL: https://api-demo.fxcm.com:443/candles/80240/m1?num=1000
|ERROR|2021-03-16 00:39:20,624|Headers: {'User-Agent': 'request', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Authorization': 'Bearer Kx7ky1Q7vfx6D46bAEMT428f4f0130d439c3d02922e4a5d4640a783830fb', 'Content-Type': 'application/x-www-form-urlencoded'}
|ERROR|2021-03-16 00:39:20,624|Params: {'num': 1000}
|ERROR|2021-03-16 00:39:20,625|Bearer token: Bearer Kx7ky1Q7vfx6D46bAEMT428f4f0130d439c3d02922e4a5d4640a783830fb
|ERROR|2021-03-16 00:39:20,625|Connection status: established
|ERROR|2021-03-16 00:39:20,625|Socket session id: Kx7ky1Q7vfx6D46bAEMT
|ERROR|2021-03-16 00:39:20,626|Can not parse server answer to json object: {"response":{"executed":false,"error":"Invalid instrument_id."},"instrument_id":0,"period_id":0,"candles":[]}.
|ERROR|2021-03-16 00:39:22,833|FXCM Server reports an unknown error: {'executed': False, 'error': ''}.
|ERROR|2021-03-16 00:39:22,834|Can not parse server answer to json object: {"response":{"executed":false,"error":""},"instrument_id":"80255","period_id":"m1","candles":[]}.
|ERROR|2021-03-16 00:39:23,268|Server reports an error: {'executed': False, 'error': 'Invalid instrument_id.'}.
|ERROR|2021-03-16 00:39:23,269|URL: https://api-demo.fxcm.com:443/candles/80259/m1?num=1000
|ERROR|2021-03-16 00:39:23,270|Headers: {'User-Agent': 'request', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Authorization': 'Bearer Kx7ky1Q7vfx6D46bAEMT428f4f0130d439c3d02922e4a5d4640a783830fb', 'Content-Type': 'application/x-www-form-urlencoded'}
|ERROR|2021-03-16 00:39:23,270|Params: {'num': 1000}
|ERROR|2021-03-16 00:39:23,271|Bearer token: Bearer Kx7ky1Q7vfx6D46bAEMT428f4f0130d439c3d02922e4a5d4640a783830fb
|ERROR|2021-03-16 00:39:23,271|Connection status: established
|ERROR|2021-03-16 00:39:23,271|Socket session id: Kx7ky1Q7vfx6D46bAEMT
|ERROR|2021-03-16 00:39:23,272|Can not parse server answer to json object: {"response":{"executed":false,"error":"Invalid instrument_id."},"instrument_id":0,"period_id":0,"candles":[]}.
|ERROR|2021-03-16 00:39:24,749|Server reports an error: {'executed': False, 'error': 'Invalid instrument_id.'}.
|ERROR|2021-03-16 00:39:24,750|URL: https://api-demo.fxcm.com:443/candles/80270/m1?num=1000
|ERROR|2021-03-16 00:39:24,751|Headers: {'User-Agent': 'request', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Authorization': 'Bearer Kx7ky1Q7vfx6D46bAEMT428f4f0130d439c3d02922e4a5d4640a783830fb', 'Content-Type': 'application/x-www-form-urlencoded'}
|ERROR|2021-03-16 00:39:24,754|Params: {'num': 1000}
|ERROR|2021-03-16 00:39:24,754|Bearer token: Bearer Kx7ky1Q7vfx6D46bAEMT428f4f0130d439c3d02922e4a5d4640a783830fb
|ERROR|2021-03-16 00:39:24,755|Connection status: established
|ERROR|2021-03-16 00:39:24,756|Socket session id: Kx7ky1Q7vfx6D46bAEMT
|ERROR|2021-03-16 00:39:24,757|Can not parse server answer to json object: {"response":{"executed":false,"error":"Invalid instrument_id."},"instrument_id":0,"period_id":0,"candles":[]}.
|ERROR|2021-03-16 00:39:25,228|FXCM Server reports an unknown error: {'executed': False, 'error': ''}.
|ERROR|2021-03-16 00:39:25,228|Can not parse server answer to json object: {"response":{"executed":false,"error":""},"instrument_id":"80273","period_id":"m1","candles":[]}.
|ERROR|2021-03-16 00:39:27,206|Server reports an error: {'executed': False, 'error': 'Invalid instrument_id.'}.
|ERROR|2021-03-16 00:39:27,206|URL: https://api-demo.fxcm.com:443/candles/80358/m1?num=1000
|ERROR|2021-03-16 00:39:27,207|Headers: {'User-Agent': 'request', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Authorization': 'Bearer Kx7ky1Q7vfx6D46bAEMT428f4f0130d439c3d02922e4a5d4640a783830fb', 'Content-Type': 'application/x-www-form-urlencoded'}
|ERROR|2021-03-16 00:39:27,207|Params: {'num': 1000}
|ERROR|2021-03-16 00:39:27,207|Bearer token: Bearer Kx7ky1Q7vfx6D46bAEMT428f4f0130d439c3d02922e4a5d4640a783830fb
|ERROR|2021-03-16 00:39:27,208|Connection status: established
|ERROR|2021-03-16 00:39:27,208|Socket session id: Kx7ky1Q7vfx6D46bAEMT
|ERROR|2021-03-16 00:39:27,208|Can not parse server answer to json object: {"response":{"executed":false,"error":"Invalid instrument_id."},"instrument_id":0,"period_id":0,"candles":[]}.
|ERROR|2021-03-16 00:39:28,913|Server reports an error: {'executed': False, 'error': 'Invalid instrument_id.'}.
|ERROR|2021-03-16 00:39:28,914|URL: https://api-demo.fxcm.com:443/candles/80366/m1?num=1000
|ERROR|2021-03-16 00:39:28,914|Headers: {'User-Agent': 'request', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Authorization': 'Bearer Kx7ky1Q7vfx6D46bAEMT428f4f0130d439c3d02922e4a5d4640a783830fb', 'Content-Type': 'application/x-www-form-urlencoded'}
|ERROR|2021-03-16 00:39:28,915|Params: {'num': 1000}
|ERROR|2021-03-16 00:39:28,916|Bearer token: Bearer Kx7ky1Q7vfx6D46bAEMT428f4f0130d439c3d02922e4a5d4640a783830fb
|ERROR|2021-03-16 00:39:28,916|Connection status: established
|ERROR|2021-03-16 00:39:28,916|Socket session id: Kx7ky1Q7vfx6D46bAEMT
|ERROR|2021-03-16 00:39:28,917|Can not parse server answer to json object: {"response":{"executed":false,"error":"Invalid instrument_id."},"instrument_id":0,"period_id":0,"candles":[]}.
|ERROR|2021-03-16 00:39:29,385|Server reports an error: {'executed': False, 'error': 'Invalid instrument_id.'}.
|ERROR|2021-03-16 00:39:29,386|URL: https://api-demo.fxcm.com:443/candles/80378/m1?num=1000
|ERROR|2021-03-16 00:39:29,387|Headers: {'User-Agent': 'request', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Authorization': 'Bearer Kx7ky1Q7vfx6D46bAEMT428f4f0130d439c3d02922e4a5d4640a783830fb', 'Content-Type': 'application/x-www-form-urlencoded'}
|ERROR|2021-03-16 00:39:29,387|Params: {'num': 1000}
|ERROR|2021-03-16 00:39:29,387|Bearer token: Bearer Kx7ky1Q7vfx6D46bAEMT428f4f0130d439c3d02922e4a5d4640a783830fb
|ERROR|2021-03-16 00:39:29,388|Connection status: established
|ERROR|2021-03-16 00:39:29,388|Socket session id: Kx7ky1Q7vfx6D46bAEMT
|ERROR|2021-03-16 00:39:29,389|Can not parse server answer to json object: {"response":{"executed":false,"error":"Invalid instrument_id."},"instrument_id":0,"period_id":0,"candles":[]}.
|ERROR|2021-03-16 00:39:30,635|Server reports an error: {'executed': False, 'error': 'Invalid instrument_id.'}.
|ERROR|2021-03-16 00:39:30,636|URL: https://api-demo.fxcm.com:443/candles/80419/m1?num=1000
|ERROR|2021-03-16 00:39:30,636|Headers: {'User-Agent': 'request', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Authorization': 'Bearer Kx7ky1Q7vfx6D46bAEMT428f4f0130d439c3d02922e4a5d4640a783830fb', 'Content-Type': 'application/x-www-form-urlencoded'}
|ERROR|2021-03-16 00:39:30,637|Params: {'num': 1000}
|ERROR|2021-03-16 00:39:30,637|Bearer token: Bearer Kx7ky1Q7vfx6D46bAEMT428f4f0130d439c3d02922e4a5d4640a783830fb
|ERROR|2021-03-16 00:39:30,637|Connection status: established
|ERROR|2021-03-16 00:39:30,638|Socket session id: Kx7ky1Q7vfx6D46bAEMT
|ERROR|2021-03-16 00:39:30,638|Can not parse server answer to json object: {"response":{"executed":false,"error":"Invalid instrument_id."},"instrument_id":0,"period_id":0,"candles":[]}.
|ERROR|2021-03-16 00:39:34,298|Server reports an error: {'executed': False, 'error': 'Invalid instrument_id.'}.
|ERROR|2021-03-16 00:39:34,300|URL: https://api-demo.fxcm.com:443/candles/80582/m1?num=1000
|ERROR|2021-03-16 00:39:34,301|Headers: {'User-Agent': 'request', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Authorization': 'Bearer Kx7ky1Q7vfx6D46bAEMT428f4f0130d439c3d02922e4a5d4640a783830fb', 'Content-Type': 'application/x-www-form-urlencoded'}
|ERROR|2021-03-16 00:39:34,302|Params: {'num': 1000}
|ERROR|2021-03-16 00:39:34,302|Bearer token: Bearer Kx7ky1Q7vfx6D46bAEMT428f4f0130d439c3d02922e4a5d4640a783830fb
|ERROR|2021-03-16 00:39:34,302|Connection status: established
|ERROR|2021-03-16 00:39:34,303|Socket session id: Kx7ky1Q7vfx6D46bAEMT
|ERROR|2021-03-16 00:39:34,303|Can not parse server answer to json object: {"response":{"executed":false,"error":"Invalid instrument_id."},"instrument_id":0,"period_id":0,"candles":[]}.
|WARNING|2021-03-16 00:40:09,387|Not Found: /admin/trader/name/18/delete/
|WARNING|2021-03-16 00:40:12,707|Not Found: /admin/trader/name/18/delete/
|ERROR|2021-03-16 00:46:33,779|Connection aborted, failed to reconnect
|ERROR|2021-03-16 00:46:34,636|Internal Server Error: /
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\Administrator\Documents\Github\OatFX\OatFX\views.py", line 25, in post
    obj.set_connection(con)
  File "C:\Users\Administrator\Documents\Github\OatFX\OatFX\shared.py", line 25, in set_connection
    self.get_instruments()
  File "C:\Users\Administrator\Documents\Github\OatFX\OatFX\shared.py", line 42, in get_instruments
    data = self.con.get_candles(symbol, period='m1', number=1000)
  File "C:\ProgramData\Anaconda3\lib\site-packages\fxcmpy\fxcmpy.py", line 2184, in get_candles
    data = self.__handle_request__(method='candles/%s/%s'
  File "C:\ProgramData\Anaconda3\lib\site-packages\fxcmpy\fxcmpy.py", line 2436, in __handle_request__
    raise IOError('Connection aborted, failed to reconnect')
OSError: Connection aborted, failed to reconnect
|ERROR|2021-03-16 00:46:41,001|packet queue is empty, aborting
|INFO|2021-03-16 00:48:35,028|C:\Users\Administrator\Documents\Github\OatFX\OatFX\shared.py changed, reloading.
|ERROR|2021-03-16 00:54:31,820|Internal Server Error: /
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\Administrator\Documents\Github\OatFX\OatFX\views.py", line 25, in post
    obj.set_connection(con)
  File "C:\Users\Administrator\Documents\Github\OatFX\OatFX\shared.py", line 25, in set_connection
    self.get_instruments()
  File "C:\Users\Administrator\Documents\Github\OatFX\OatFX\shared.py", line 47, in get_instruments
    p = pair(symbol = symbol, open = _opens, high = _highs, low = _lows, close = _closes, tickqty = _tickqty, timestamp = _timestamp)
NameError: name 'symbol' is not defined
|INFO|2021-03-16 00:55:45,841|C:\Users\Administrator\Documents\Github\OatFX\OatFX\shared.py changed, reloading.
|INFO|2021-03-16 01:32:51,065|C:\Users\Administrator\Documents\Github\OatFX\OatFX\shared.py changed, reloading.
|ERROR|2021-03-16 01:55:14,928|Socket returns unknown error.
|ERROR|2021-03-16 01:55:15,619|Internal Server Error: /
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\Administrator\Documents\Github\OatFX\OatFX\views.py", line 24, in post
    con = obj.fx(access_token=token, log_level='error', server='demo', log_file='oatfx.log')
  File "C:\ProgramData\Anaconda3\lib\site-packages\fxcmpy\fxcmpy.py", line 218, in __init__
    raise ServerError('Can not connect to FXCM Server.')
fxcmpy.fxcmpy.ServerError: Can not connect to FXCM Server.
|ERROR|2021-03-16 01:55:58,939|Socket returns unknown error.
|ERROR|2021-03-16 01:55:59,275|Internal Server Error: /
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\Administrator\Documents\Github\OatFX\OatFX\views.py", line 24, in post
    con = obj.fx(access_token=token, log_level='error', server='demo', log_file='oatfx.log')
  File "C:\ProgramData\Anaconda3\lib\site-packages\fxcmpy\fxcmpy.py", line 218, in __init__
    raise ServerError('Can not connect to FXCM Server.')
fxcmpy.fxcmpy.ServerError: Can not connect to FXCM Server.
|INFO|2021-03-16 02:22:22,721|C:\Users\Administrator\Documents\Github\OatFX\OatFX\shared.py changed, reloading.
|INFO|2021-03-16 02:26:46,201|C:\Users\Administrator\Documents\Github\OatFX\OatFX\shared.py changed, reloading.
|INFO|2021-03-16 02:29:43,698|C:\Users\Administrator\Documents\Github\OatFX\OatFX\shared.py changed, reloading.
|INFO|2021-03-16 02:31:24,509|C:\Users\Administrator\Documents\Github\OatFX\OatFX\shared.py changed, reloading.
|INFO|2021-03-16 02:36:50,048|C:\Users\Administrator\Documents\Github\OatFX\OatFX\shared.py changed, reloading.
|ERROR|2021-03-16 07:46:42,623|Internal Server Error: /
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\Administrator\Documents\Github\OatFX\OatFX\views.py", line 25, in post
    obj.set_connection(con)
  File "C:\Users\Administrator\Documents\Github\OatFX\OatFX\shared.py", line 26, in set_connection
    self.get_instruments()
  File "C:\Users\Administrator\Documents\Github\OatFX\OatFX\shared.py", line 59, in get_instruments
    con.subscribe_market_data(sbl)
NameError: name 'con' is not defined
|INFO|2021-03-16 07:48:04,509|C:\Users\Administrator\Documents\Github\OatFX\OatFX\shared.py changed, reloading.
|WARNING|2021-03-16 07:56:37,230|Bad Request: /close_connection
|INFO|2021-03-16 08:41:18,452|C:\Users\Administrator\Documents\Github\OatFX\OatFX\shared.py changed, reloading.
|INFO|2021-03-16 09:11:14,919|C:\Users\Administrator\Documents\Github\OatFX\OatFX\shared.py changed, reloading.
|ERROR|2021-03-16 18:25:51,102|Socket returns unknown error.
|ERROR|2021-03-16 18:25:52,504|Internal Server Error: /
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\Administrator\Documents\Github\OatFX\OatFX\views.py", line 24, in post
    con = obj.fx(access_token=token, log_level='error', server='demo', log_file='oatfx.log')
  File "C:\ProgramData\Anaconda3\lib\site-packages\fxcmpy\fxcmpy.py", line 218, in __init__
    raise ServerError('Can not connect to FXCM Server.')
fxcmpy.fxcmpy.ServerError: Can not connect to FXCM Server.
|ERROR|2021-03-16 18:26:27,594|Socket returns unknown error.
|ERROR|2021-03-16 18:26:27,930|Internal Server Error: /
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\Administrator\Documents\Github\OatFX\OatFX\views.py", line 24, in post
    con = obj.fx(access_token=token, log_level='error', server='demo', log_file='oatfx.log')
  File "C:\ProgramData\Anaconda3\lib\site-packages\fxcmpy\fxcmpy.py", line 218, in __init__
    raise ServerError('Can not connect to FXCM Server.')
fxcmpy.fxcmpy.ServerError: Can not connect to FXCM Server.
|WARNING|2021-03-16 18:27:04,374|Bad Request: /close_connection
|ERROR|2021-03-16 18:27:18,164|Socket returns unknown error.
|ERROR|2021-03-16 18:27:19,670|Internal Server Error: /
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\Administrator\Documents\Github\OatFX\OatFX\views.py", line 24, in post
    con = obj.fx(access_token=token, log_level='error', server='demo', log_file='oatfx.log')
  File "C:\ProgramData\Anaconda3\lib\site-packages\fxcmpy\fxcmpy.py", line 218, in __init__
    raise ServerError('Can not connect to FXCM Server.')
fxcmpy.fxcmpy.ServerError: Can not connect to FXCM Server.
|ERROR|2021-03-16 18:37:03,108|Call of update raised an error:
|ERROR|2021-03-16 18:37:03,109|<class 'UnboundLocalError'>
|ERROR|2021-03-16 18:37:03,109|local variable '_close' referenced before assignment
|ERROR|2021-03-16 18:37:04,103|Call of update raised an error:
|ERROR|2021-03-16 18:37:04,104|<class 'UnboundLocalError'>
|ERROR|2021-03-16 18:37:04,104|local variable '_close' referenced before assignment
|ERROR|2021-03-16 18:37:05,647|Call of update raised an error:
|ERROR|2021-03-16 18:37:05,650|<class 'UnboundLocalError'>
|ERROR|2021-03-16 18:37:05,659|local variable '_close' referenced before assignment
|ERROR|2021-03-16 18:37:05,681|Call of update raised an error:
|ERROR|2021-03-16 18:37:05,682|<class 'UnboundLocalError'>
|ERROR|2021-03-16 18:37:05,682|local variable '_close' referenced before assignment
|ERROR|2021-03-16 18:37:14,601|Call of update raised an error:
|ERROR|2021-03-16 18:37:14,638|Call of update raised an error:
|ERROR|2021-03-16 18:37:14,647|Call of update raised an error:
|ERROR|2021-03-16 18:37:14,648|<class 'UnboundLocalError'>
|ERROR|2021-03-16 18:37:14,654|Call of update raised an error:
|ERROR|2021-03-16 18:37:14,661|Call of update raised an error:
|ERROR|2021-03-16 18:37:14,700|<class 'UnboundLocalError'>
|ERROR|2021-03-16 18:37:14,688|<class 'UnboundLocalError'>
|ERROR|2021-03-16 18:37:14,696|Call of update raised an error:
|ERROR|2021-03-16 18:37:14,697|local variable '_close' referenced before assignment
|ERROR|2021-03-16 18:37:14,698|<class 'UnboundLocalError'>
|ERROR|2021-03-16 18:37:14,676|<class 'UnboundLocalError'>
|ERROR|2021-03-16 18:37:14,701|local variable '_close' referenced before assignment
|ERROR|2021-03-16 18:37:14,701|local variable '_close' referenced before assignment
|ERROR|2021-03-16 18:37:14,702|<class 'UnboundLocalError'>
|ERROR|2021-03-16 18:37:14,703|local variable '_close' referenced before assignment
|ERROR|2021-03-16 18:37:14,703|local variable '_close' referenced before assignment
|ERROR|2021-03-16 18:37:14,705|local variable '_close' referenced before assignment
|ERROR|2021-03-16 18:37:18,224|Call of update raised an error:
|ERROR|2021-03-16 18:37:18,323|<class 'UnboundLocalError'>
|ERROR|2021-03-16 18:37:18,324|local variable '_close' referenced before assignment
|ERROR|2021-03-16 18:37:32,461|Call of update raised an error:
|ERROR|2021-03-16 18:37:32,481|<class 'UnboundLocalError'>
|ERROR|2021-03-16 18:37:32,481|local variable '_close' referenced before assignment
|ERROR|2021-03-16 18:37:32,475|Call of update raised an error:
|ERROR|2021-03-16 18:37:32,480|Call of update raised an error:
|ERROR|2021-03-16 18:37:32,482|<class 'UnboundLocalError'>
|ERROR|2021-03-16 18:37:32,484|local variable '_close' referenced before assignment
|ERROR|2021-03-16 18:37:32,483|<class 'UnboundLocalError'>
|ERROR|2021-03-16 18:37:32,484|local variable '_close' referenced before assignment
|ERROR|2021-03-16 18:37:40,454|Call of update raised an error:
|ERROR|2021-03-16 18:37:40,466|<class 'UnboundLocalError'>
|ERROR|2021-03-16 18:37:40,487|Call of update raised an error:
|ERROR|2021-03-16 18:37:40,487|local variable '_close' referenced before assignment
|ERROR|2021-03-16 18:37:40,487|<class 'UnboundLocalError'>
|ERROR|2021-03-16 18:37:40,489|local variable '_close' referenced before assignment
|ERROR|2021-03-16 18:37:40,707|Call of update raised an error:
|ERROR|2021-03-16 18:37:40,707|<class 'UnboundLocalError'>
|ERROR|2021-03-16 18:37:40,707|local variable '_close' referenced before assignment
|ERROR|2021-03-16 18:37:41,211|Call of update raised an error:
|ERROR|2021-03-16 18:37:41,212|<class 'UnboundLocalError'>
|ERROR|2021-03-16 18:37:41,213|local variable '_close' referenced before assignment
|ERROR|2021-03-16 18:37:48,302|Server reports an error: {'executed': False, 'error': 'Unauthorized'}.
|ERROR|2021-03-16 18:37:48,303|URL: https://api-demo.fxcm.com:443/candles/1/m1?num=1
|ERROR|2021-03-16 18:37:48,304|Headers: {'User-Agent': 'request', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Authorization': 'Bearer N4b3L58D71HGiLt5AHy7428f4f0130d439c3d02922e4a5d4640a783830fb', 'Content-Type': 'application/x-www-form-urlencoded'}
|ERROR|2021-03-16 18:37:48,305|Params: {'num': 1}
|ERROR|2021-03-16 18:37:48,307|Bearer token: Bearer N4b3L58D71HGiLt5AHy7428f4f0130d439c3d02922e4a5d4640a783830fb
|ERROR|2021-03-16 18:37:48,307|Connection status: established
|ERROR|2021-03-16 18:37:48,308|Socket session id: N4b3L58D71HGiLt5AHy7
|ERROR|2021-03-16 18:37:48,308|Can not parse server answer to json object: {"response":{"executed":false,"error":"Unauthorized"},"instrument_id":0,"period_id":0,"candles":[]}.
|ERROR|2021-03-16 18:37:48,418|Call of update raised an error:
|ERROR|2021-03-16 18:37:48,419|<class 'IndexError'>
|ERROR|2021-03-16 18:37:48,419|list index out of range
|ERROR|2021-03-16 18:37:49,715|Server reports an error: {'executed': False, 'error': 'Unauthorized'}.
|ERROR|2021-03-16 18:37:49,715|URL: https://api-demo.fxcm.com:443/candles/1/m1?num=1
|ERROR|2021-03-16 18:37:49,716|Headers: {'User-Agent': 'request', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Authorization': 'Bearer N4b3L58D71HGiLt5AHy7428f4f0130d439c3d02922e4a5d4640a783830fb', 'Content-Type': 'application/x-www-form-urlencoded'}
|ERROR|2021-03-16 18:37:49,716|Params: {'num': 1}
|ERROR|2021-03-16 18:37:49,717|Bearer token: Bearer N4b3L58D71HGiLt5AHy7428f4f0130d439c3d02922e4a5d4640a783830fb
|ERROR|2021-03-16 18:37:49,717|Connection status: established
|ERROR|2021-03-16 18:37:49,717|Socket session id: N4b3L58D71HGiLt5AHy7
|ERROR|2021-03-16 18:37:49,718|Can not parse server answer to json object: {"response":{"executed":false,"error":"Unauthorized"},"instrument_id":0,"period_id":0,"candles":[]}.
|ERROR|2021-03-16 18:37:49,776|Call of update raised an error:
|ERROR|2021-03-16 18:37:49,776|<class 'IndexError'>
|ERROR|2021-03-16 18:37:49,776|list index out of range
|ERROR|2021-03-16 18:37:55,557|FXCM reject req candles/1/m1 with status 520 and msg <!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en-US"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en-US"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en-US"> <!--<![endif]-->
<head>
<meta http-equiv="refresh" content="0">

<title>api-demo.fxcm.com | 520: Web server is returning an unknown error</title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/main.css" type="text/css" media="screen,projection" />


</head>
<body>
<div id="cf-wrapper">

    

    <div id="cf-error-details" class="p-0">
        <header class="mx-auto pt-10 lg:pt-6 lg:px-8 w-240 lg:w-full mb-8">
            <h1 class="inline-block sm:block sm:mb-2 font-light text-60 lg:text-4xl text-black-dark leading-tight mr-2">
              
              <span class="cf-error-type">Error</span>
              <span class="cf-error-code">520</span>
            </h1>
            <span class="inline-block sm:block font-mono text-15 lg:text-sm lg:leading-relaxed">Ray ID: 630fc0a54f68c4f8 &bull;</span>
            <span class="inline-block sm:block font-mono text-15 lg:text-sm lg:leading-relaxed">2021-03-16 17:37:59 UTC</span>
            <h2 class="text-gray-600 leading-1.3 text-3xl font-light">Web server is returning an unknown error</h2>
        </header>
        
        <div class="my-8 bg-gradient-gray">
            <div class="w-240 lg:w-full mx-auto">
                <div class="clearfix md:px-8">
                  
<div id="cf-browser-status" class=" relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center">
  <div class="relative mb-10 md:m-0">
    <span class="cf-icon-browser block md:hidden h-20 bg-center bg-no-repeat"></span>
    <span class="cf-icon-ok w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span>
  </div>
  <span class="md:block w-full truncate">You</span>
  <h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3">Browser</h3>
  <span class="leading-1.3 text-2xl text-green-success">Working</span>
</div>

<div id="cf-cloudflare-status" class=" relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center">
  <div class="relative mb-10 md:m-0">
    <span class="cf-icon-cloud block md:hidden h-20 bg-center bg-no-repeat"></span>
    <span class="cf-icon-ok w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span>
  </div>
  <span class="md:block w-full truncate">Lagos</span>
  <h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3">Cloudflare</h3>
  <span class="leading-1.3 text-2xl text-green-success">Working</span>
</div>

<div id="cf-host-status" class="cf-error-source relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center">
  <div class="relative mb-10 md:m-0">
    <span class="cf-icon-server block md:hidden h-20 bg-center bg-no-repeat"></span>
    <span class="cf-icon-error w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span>
  </div>
  <span class="md:block w-full truncate">api-demo.fxcm.com</span>
  <h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3">Host</h3>
  <span class="leading-1.3 text-2xl text-red-error">Error</span>
</div>

                </div>
              
            </div>
        </div>

        <div class="w-240 lg:w-full mx-auto mb-8 lg:px-8">
            <div class="clearfix">
                <div class="w-1/2 md:w-full float-left pr-6 md:pb-10 md:pr-0 leading-relaxed">
                    <h2 class="text-3xl font-normal leading-1.3 mb-4">What happened?</h2>
                    <p>There is an unknown connection issue between Cloudflare and the origin web server. As a result, the web page can not be displayed.</p>
                </div>
              
                <div class="w-1/2 md:w-full float-left leading-relaxed">
                    <h2 class="text-3xl font-normal leading-1.3 mb-4">What can I do?</h2>
                          <h3 class="text-15 font-semibold mb-2">If you are a visitor of this website:</h3>
      <p class="mb-6">Please try again in a few minutes.</p>

      <h3 class="text-15 font-semibold mb-2">If you are the owner of this website:</h3>
      <p><span>There is an issue between Cloudflare's cache and your origin web server. Cloudflare monitors for these errors and automatically investigates the cause. To help support the investigation, you can pull the corresponding error log from your web server and submit it our support team.  Please include the Ray ID (which is at the bottom of this error page).</span> <a rel="noopener noreferrer" href="https://support.cloudflare.com/hc/en-us/articles/200171936-Error-520">Additional troubleshooting resources</a>.</p>
                </div>
            </div>
              
        </div>

        <div class="cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center sm:text-left border-solid border-0 border-t border-gray-300">
  <p class="text-13">
    <span class="cf-footer-item sm:block sm:mb-1">Cloudflare Ray ID: <strong class="font-semibold">630fc0a54f68c4f8</strong></span>
    <span class="cf-footer-separator sm:hidden">&bull;</span>
    <span class="cf-footer-item sm:block sm:mb-1"><span>Your IP</span>: 105.112.38.242</span>
    <span class="cf-footer-separator sm:hidden">&bull;</span>
    <span class="cf-footer-item sm:block sm:mb-1"><span>Performance &amp; security by</span> <a rel="noopener noreferrer" href="https://www.cloudflare.com/5xx-error-landing" id="brand_link" target="_blank">Cloudflare</a></span>
    
  </p>
</div><!-- /.error-footer -->


    </div>
</div>
</body>
</html>

.
|ERROR|2021-03-16 18:37:55,558|Call of update raised an error:
|ERROR|2021-03-16 18:37:55,560|<class 'fxcmpy.fxcmpy.ServerError'>
|ERROR|2021-03-16 18:37:55,560|Request returns status code 520 and message "<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en-US"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en-US"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en-US"> <!--<![endif]-->
<head>
<meta http-equiv="refresh" content="0">

<title>api-demo.fxcm.com | 520: Web server is returning an unknown error</title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/main.css" type="text/css" media="screen,projection" />


</head>
<body>
<div id="cf-wrapper">

    

    <div id="cf-error-details" class="p-0">
        <header class="mx-auto pt-10 lg:pt-6 lg:px-8 w-240 lg:w-full mb-8">
            <h1 class="inline-block sm:block sm:mb-2 font-light text-60 lg:text-4xl text-black-dark leading-tight mr-2">
              
              <span class="cf-error-type">Error</span>
              <span class="cf-error-code">520</span>
            </h1>
            <span class="inline-block sm:block font-mono text-15 lg:text-sm lg:leading-relaxed">Ray ID: 630fc0a54f68c4f8 &bull;</span>
            <span class="inline-block sm:block font-mono text-15 lg:text-sm lg:leading-relaxed">2021-03-16 17:37:59 UTC</span>
            <h2 class="text-gray-600 leading-1.3 text-3xl font-light">Web server is returning an unknown error</h2>
        </header>
        
        <div class="my-8 bg-gradient-gray">
            <div class="w-240 lg:w-full mx-auto">
                <div class="clearfix md:px-8">
                  
<div id="cf-browser-status" class=" relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center">
  <div class="relative mb-10 md:m-0">
    <span class="cf-icon-browser block md:hidden h-20 bg-center bg-no-repeat"></span>
    <span class="cf-icon-ok w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span>
  </div>
  <span class="md:block w-full truncate">You</span>
  <h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3">Browser</h3>
  <span class="leading-1.3 text-2xl text-green-success">Working</span>
</div>

<div id="cf-cloudflare-status" class=" relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center">
  <div class="relative mb-10 md:m-0">
    <span class="cf-icon-cloud block md:hidden h-20 bg-center bg-no-repeat"></span>
    <span class="cf-icon-ok w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span>
  </div>
  <span class="md:block w-full truncate">Lagos</span>
  <h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3">Cloudflare</h3>
  <span class="leading-1.3 text-2xl text-green-success">Working</span>
</div>

<div id="cf-host-status" class="cf-error-source relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center">
  <div class="relative mb-10 md:m-0">
    <span class="cf-icon-server block md:hidden h-20 bg-center bg-no-repeat"></span>
    <span class="cf-icon-error w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span>
  </div>
  <span class="md:block w-full truncate">api-demo.fxcm.com</span>
  <h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3">Host</h3>
  <span class="leading-1.3 text-2xl text-red-error">Error</span>
</div>

                </div>
              
            </div>
        </div>

        <div class="w-240 lg:w-full mx-auto mb-8 lg:px-8">
            <div class="clearfix">
                <div class="w-1/2 md:w-full float-left pr-6 md:pb-10 md:pr-0 leading-relaxed">
                    <h2 class="text-3xl font-normal leading-1.3 mb-4">What happened?</h2>
                    <p>There is an unknown connection issue between Cloudflare and the origin web server. As a result, the web page can not be displayed.</p>
                </div>
              
                <div class="w-1/2 md:w-full float-left leading-relaxed">
                    <h2 class="text-3xl font-normal leading-1.3 mb-4">What can I do?</h2>
                          <h3 class="text-15 font-semibold mb-2">If you are a visitor of this website:</h3>
      <p class="mb-6">Please try again in a few minutes.</p>

      <h3 class="text-15 font-semibold mb-2">If you are the owner of this website:</h3>
      <p><span>There is an issue between Cloudflare's cache and your origin web server. Cloudflare monitors for these errors and automatically investigates the cause. To help support the investigation, you can pull the corresponding error log from your web server and submit it our support team.  Please include the Ray ID (which is at the bottom of this error page).</span> <a rel="noopener noreferrer" href="https://support.cloudflare.com/hc/en-us/articles/200171936-Error-520">Additional troubleshooting resources</a>.</p>
                </div>
            </div>
              
        </div>

        <div class="cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center sm:text-left border-solid border-0 border-t border-gray-300">
  <p class="text-13">
    <span class="cf-footer-item sm:block sm:mb-1">Cloudflare Ray ID: <strong class="font-semibold">630fc0a54f68c4f8</strong></span>
    <span class="cf-footer-separator sm:hidden">&bull;</span>
    <span class="cf-footer-item sm:block sm:mb-1"><span>Your IP</span>: 105.112.38.242</span>
    <span class="cf-footer-separator sm:hidden">&bull;</span>
    <span class="cf-footer-item sm:block sm:mb-1"><span>Performance &amp; security by</span> <a rel="noopener noreferrer" href="https://www.cloudflare.com/5xx-error-landing" id="brand_link" target="_blank">Cloudflare</a></span>
    
  </p>
</div><!-- /.error-footer -->


    </div>
</div>
</body>
</html>

"
|ERROR|2021-03-16 18:37:56,924|Server reports an error: {'executed': False, 'error': 'Unauthorized'}.
|ERROR|2021-03-16 18:37:56,925|URL: https://api-demo.fxcm.com:443/candles/1/m1?num=1
|ERROR|2021-03-16 18:37:56,925|Headers: {'User-Agent': 'request', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Authorization': 'Bearer N4b3L58D71HGiLt5AHy7428f4f0130d439c3d02922e4a5d4640a783830fb', 'Content-Type': 'application/x-www-form-urlencoded'}
|ERROR|2021-03-16 18:37:56,926|Params: {'num': 1}
|ERROR|2021-03-16 18:37:56,926|Bearer token: Bearer N4b3L58D71HGiLt5AHy7428f4f0130d439c3d02922e4a5d4640a783830fb
|ERROR|2021-03-16 18:37:56,926|Connection status: established
|ERROR|2021-03-16 18:37:56,927|Socket session id: N4b3L58D71HGiLt5AHy7
|ERROR|2021-03-16 18:37:56,927|Can not parse server answer to json object: {"response":{"executed":false,"error":"Unauthorized"},"instrument_id":0,"period_id":0,"candles":[]}.
|ERROR|2021-03-16 18:37:56,953|Call of update raised an error:
|ERROR|2021-03-16 18:37:56,953|<class 'IndexError'>
|ERROR|2021-03-16 18:37:56,953|list index out of range
|ERROR|2021-03-16 18:37:57,001|Server reports an error: {'executed': False, 'error': 'Unauthorized'}.
|ERROR|2021-03-16 18:37:57,001|URL: https://api-demo.fxcm.com:443/candles/1/m1?num=1
|ERROR|2021-03-16 18:37:57,002|Headers: {'User-Agent': 'request', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Authorization': 'Bearer N4b3L58D71HGiLt5AHy7428f4f0130d439c3d02922e4a5d4640a783830fb', 'Content-Type': 'application/x-www-form-urlencoded'}
|ERROR|2021-03-16 18:37:57,002|Params: {'num': 1}
|ERROR|2021-03-16 18:37:57,003|Bearer token: Bearer N4b3L58D71HGiLt5AHy7428f4f0130d439c3d02922e4a5d4640a783830fb
|ERROR|2021-03-16 18:37:57,003|Connection status: established
|ERROR|2021-03-16 18:37:57,003|Socket session id: N4b3L58D71HGiLt5AHy7
|ERROR|2021-03-16 18:37:57,004|Can not parse server answer to json object: {"response":{"executed":false,"error":"Unauthorized"},"instrument_id":0,"period_id":0,"candles":[]}.
|ERROR|2021-03-16 18:37:57,029|Call of update raised an error:
|ERROR|2021-03-16 18:37:57,030|<class 'IndexError'>
|ERROR|2021-03-16 18:37:57,030|list index out of range
|ERROR|2021-03-16 18:37:59,264|Server reports an error: {'executed': False, 'error': 'Unauthorized'}.
|ERROR|2021-03-16 18:37:59,265|URL: https://api-demo.fxcm.com:443/candles/1/m1?num=1
|ERROR|2021-03-16 18:37:59,266|Headers: {'User-Agent': 'request', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Authorization': 'Bearer N4b3L58D71HGiLt5AHy7428f4f0130d439c3d02922e4a5d4640a783830fb', 'Content-Type': 'application/x-www-form-urlencoded'}
|ERROR|2021-03-16 18:37:59,269|Params: {'num': 1}
|ERROR|2021-03-16 18:37:59,270|Bearer token: Bearer N4b3L58D71HGiLt5AHy7428f4f0130d439c3d02922e4a5d4640a783830fb
|ERROR|2021-03-16 18:37:59,270|Connection status: established
|ERROR|2021-03-16 18:37:59,270|Socket session id: N4b3L58D71HGiLt5AHy7
|ERROR|2021-03-16 18:37:59,270|Can not parse server answer to json object: {"response":{"executed":false,"error":"Unauthorized"},"instrument_id":0,"period_id":0,"candles":[]}.
|ERROR|2021-03-16 18:37:59,318|Call of update raised an error:
|ERROR|2021-03-16 18:37:59,320|<class 'IndexError'>
|ERROR|2021-03-16 18:37:59,321|list index out of range
|ERROR|2021-03-16 18:38:00,106|Server reports an error: {'executed': False, 'error': 'Unauthorized'}.
|ERROR|2021-03-16 18:38:00,106|URL: https://api-demo.fxcm.com:443/candles/1/m1?num=1
|ERROR|2021-03-16 18:38:00,107|Headers: {'User-Agent': 'request', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Authorization': 'Bearer N4b3L58D71HGiLt5AHy7428f4f0130d439c3d02922e4a5d4640a783830fb', 'Content-Type': 'application/x-www-form-urlencoded'}
|ERROR|2021-03-16 18:38:00,107|Params: {'num': 1}
|ERROR|2021-03-16 18:38:00,108|Bearer token: Bearer N4b3L58D71HGiLt5AHy7428f4f0130d439c3d02922e4a5d4640a783830fb
|ERROR|2021-03-16 18:38:00,109|Connection status: established
|ERROR|2021-03-16 18:38:00,109|Socket session id: N4b3L58D71HGiLt5AHy7
|ERROR|2021-03-16 18:38:00,110|Can not parse server answer to json object: {"response":{"executed":false,"error":"Unauthorized"},"instrument_id":0,"period_id":0,"candles":[]}.
|ERROR|2021-03-16 18:38:00,142|Call of update raised an error:
|ERROR|2021-03-16 18:38:00,143|<class 'IndexError'>
|ERROR|2021-03-16 18:38:00,143|list index out of range
|ERROR|2021-03-16 18:38:00,213|Server reports an error: {'executed': False, 'error': 'Unauthorized'}.
|ERROR|2021-03-16 18:38:00,214|URL: https://api-demo.fxcm.com:443/candles/1/m1?num=1
|ERROR|2021-03-16 18:38:00,214|Headers: {'User-Agent': 'request', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Authorization': 'Bearer N4b3L58D71HGiLt5AHy7428f4f0130d439c3d02922e4a5d4640a783830fb', 'Content-Type': 'application/x-www-form-urlencoded'}
|ERROR|2021-03-16 18:38:00,214|Params: {'num': 1}
|ERROR|2021-03-16 18:38:00,215|Bearer token: Bearer N4b3L58D71HGiLt5AHy7428f4f0130d439c3d02922e4a5d4640a783830fb
|ERROR|2021-03-16 18:38:00,215|Connection status: established
|ERROR|2021-03-16 18:38:00,215|Socket session id: N4b3L58D71HGiLt5AHy7
|ERROR|2021-03-16 18:38:00,216|Can not parse server answer to json object: {"response":{"executed":false,"error":"Unauthorized"},"instrument_id":0,"period_id":0,"candles":[]}.
|ERROR|2021-03-16 18:38:00,243|Call of update raised an error:
|ERROR|2021-03-16 18:38:00,243|<class 'IndexError'>
|ERROR|2021-03-16 18:38:00,244|list index out of range
|ERROR|2021-03-16 18:38:03,725|Server reports an error: {'executed': False, 'error': 'Unauthorized'}.
|ERROR|2021-03-16 18:38:03,725|URL: https://api-demo.fxcm.com:443/candles/1/m1?num=1
|ERROR|2021-03-16 18:38:03,726|Headers: {'User-Agent': 'request', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Authorization': 'Bearer N4b3L58D71HGiLt5AHy7428f4f0130d439c3d02922e4a5d4640a783830fb', 'Content-Type': 'application/x-www-form-urlencoded'}
|ERROR|2021-03-16 18:38:03,726|Params: {'num': 1}
|ERROR|2021-03-16 18:38:03,726|Bearer token: Bearer N4b3L58D71HGiLt5AHy7428f4f0130d439c3d02922e4a5d4640a783830fb
|ERROR|2021-03-16 18:38:03,727|Connection status: established
|ERROR|2021-03-16 18:38:03,727|Socket session id: N4b3L58D71HGiLt5AHy7
|ERROR|2021-03-16 18:38:03,727|Can not parse server answer to json object: {"response":{"executed":false,"error":"Unauthorized"},"instrument_id":0,"period_id":0,"candles":[]}.
|ERROR|2021-03-16 18:38:03,759|Call of update raised an error:
|ERROR|2021-03-16 18:38:03,760|<class 'IndexError'>
|ERROR|2021-03-16 18:38:03,760|list index out of range
|INFO|2021-03-16 18:57:17,784|C:\Users\Administrator\Documents\Github\OatFX\OatFX\shared.py changed, reloading.
|ERROR|2021-03-16 19:00:10,659|Call of update raised an error:
|ERROR|2021-03-16 19:00:10,660|<class 'UnboundLocalError'>
|ERROR|2021-03-16 19:00:10,661|local variable '_close' referenced before assignment
|ERROR|2021-03-16 19:00:10,830|FXCM reject req candles/3/m1 with status 520 and msg <!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en-US"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en-US"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en-US"> <!--<![endif]-->
<head>
<meta http-equiv="refresh" content="0">

<title>api-demo.fxcm.com | 520: Web server is returning an unknown error</title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/main.css" type="text/css" media="screen,projection" />


</head>
<body>
<div id="cf-wrapper">

    

    <div id="cf-error-details" class="p-0">
        <header class="mx-auto pt-10 lg:pt-6 lg:px-8 w-240 lg:w-full mb-8">
            <h1 class="inline-block sm:block sm:mb-2 font-light text-60 lg:text-4xl text-black-dark leading-tight mr-2">
              
              <span class="cf-error-type">Error</span>
              <span class="cf-error-code">520</span>
            </h1>
            <span class="inline-block sm:block font-mono text-15 lg:text-sm lg:leading-relaxed">Ray ID: 630fe1427fd8c4ec &bull;</span>
            <span class="inline-block sm:block font-mono text-15 lg:text-sm lg:leading-relaxed">2021-03-16 18:00:14 UTC</span>
            <h2 class="text-gray-600 leading-1.3 text-3xl font-light">Web server is returning an unknown error</h2>
        </header>
        
        <div class="my-8 bg-gradient-gray">
            <div class="w-240 lg:w-full mx-auto">
                <div class="clearfix md:px-8">
                  
<div id="cf-browser-status" class=" relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center">
  <div class="relative mb-10 md:m-0">
    <span class="cf-icon-browser block md:hidden h-20 bg-center bg-no-repeat"></span>
    <span class="cf-icon-ok w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span>
  </div>
  <span class="md:block w-full truncate">You</span>
  <h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3">Browser</h3>
  <span class="leading-1.3 text-2xl text-green-success">Working</span>
</div>

<div id="cf-cloudflare-status" class=" relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center">
  <div class="relative mb-10 md:m-0">
    <span class="cf-icon-cloud block md:hidden h-20 bg-center bg-no-repeat"></span>
    <span class="cf-icon-ok w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span>
  </div>
  <span class="md:block w-full truncate">Lagos</span>
  <h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3">Cloudflare</h3>
  <span class="leading-1.3 text-2xl text-green-success">Working</span>
</div>

<div id="cf-host-status" class="cf-error-source relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center">
  <div class="relative mb-10 md:m-0">
    <span class="cf-icon-server block md:hidden h-20 bg-center bg-no-repeat"></span>
    <span class="cf-icon-error w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span>
  </div>
  <span class="md:block w-full truncate">api-demo.fxcm.com</span>
  <h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3">Host</h3>
  <span class="leading-1.3 text-2xl text-red-error">Error</span>
</div>

                </div>
              
            </div>
        </div>

        <div class="w-240 lg:w-full mx-auto mb-8 lg:px-8">
            <div class="clearfix">
                <div class="w-1/2 md:w-full float-left pr-6 md:pb-10 md:pr-0 leading-relaxed">
                    <h2 class="text-3xl font-normal leading-1.3 mb-4">What happened?</h2>
                    <p>There is an unknown connection issue between Cloudflare and the origin web server. As a result, the web page can not be displayed.</p>
                </div>
              
                <div class="w-1/2 md:w-full float-left leading-relaxed">
                    <h2 class="text-3xl font-normal leading-1.3 mb-4">What can I do?</h2>
                          <h3 class="text-15 font-semibold mb-2">If you are a visitor of this website:</h3>
      <p class="mb-6">Please try again in a few minutes.</p>

      <h3 class="text-15 font-semibold mb-2">If you are the owner of this website:</h3>
      <p><span>There is an issue between Cloudflare's cache and your origin web server. Cloudflare monitors for these errors and automatically investigates the cause. To help support the investigation, you can pull the corresponding error log from your web server and submit it our support team.  Please include the Ray ID (which is at the bottom of this error page).</span> <a rel="noopener noreferrer" href="https://support.cloudflare.com/hc/en-us/articles/200171936-Error-520">Additional troubleshooting resources</a>.</p>
                </div>
            </div>
              
        </div>

        <div class="cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center sm:text-left border-solid border-0 border-t border-gray-300">
  <p class="text-13">
    <span class="cf-footer-item sm:block sm:mb-1">Cloudflare Ray ID: <strong class="font-semibold">630fe1427fd8c4ec</strong></span>
    <span class="cf-footer-separator sm:hidden">&bull;</span>
    <span class="cf-footer-item sm:block sm:mb-1"><span>Your IP</span>: 105.112.38.242</span>
    <span class="cf-footer-separator sm:hidden">&bull;</span>
    <span class="cf-footer-item sm:block sm:mb-1"><span>Performance &amp; security by</span> <a rel="noopener noreferrer" href="https://www.cloudflare.com/5xx-error-landing" id="brand_link" target="_blank">Cloudflare</a></span>
    
  </p>
</div><!-- /.error-footer -->


    </div>
</div>
</body>
</html>

.
|ERROR|2021-03-16 19:00:10,831|Call of update raised an error:
|ERROR|2021-03-16 19:00:10,832|<class 'fxcmpy.fxcmpy.ServerError'>
|ERROR|2021-03-16 19:00:10,832|Request returns status code 520 and message "<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en-US"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en-US"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en-US"> <!--<![endif]-->
<head>
<meta http-equiv="refresh" content="0">

<title>api-demo.fxcm.com | 520: Web server is returning an unknown error</title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/main.css" type="text/css" media="screen,projection" />


</head>
<body>
<div id="cf-wrapper">

    

    <div id="cf-error-details" class="p-0">
        <header class="mx-auto pt-10 lg:pt-6 lg:px-8 w-240 lg:w-full mb-8">
            <h1 class="inline-block sm:block sm:mb-2 font-light text-60 lg:text-4xl text-black-dark leading-tight mr-2">
              
              <span class="cf-error-type">Error</span>
              <span class="cf-error-code">520</span>
            </h1>
            <span class="inline-block sm:block font-mono text-15 lg:text-sm lg:leading-relaxed">Ray ID: 630fe1427fd8c4ec &bull;</span>
            <span class="inline-block sm:block font-mono text-15 lg:text-sm lg:leading-relaxed">2021-03-16 18:00:14 UTC</span>
            <h2 class="text-gray-600 leading-1.3 text-3xl font-light">Web server is returning an unknown error</h2>
        </header>
        
        <div class="my-8 bg-gradient-gray">
            <div class="w-240 lg:w-full mx-auto">
                <div class="clearfix md:px-8">
                  
<div id="cf-browser-status" class=" relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center">
  <div class="relative mb-10 md:m-0">
    <span class="cf-icon-browser block md:hidden h-20 bg-center bg-no-repeat"></span>
    <span class="cf-icon-ok w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span>
  </div>
  <span class="md:block w-full truncate">You</span>
  <h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3">Browser</h3>
  <span class="leading-1.3 text-2xl text-green-success">Working</span>
</div>

<div id="cf-cloudflare-status" class=" relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center">
  <div class="relative mb-10 md:m-0">
    <span class="cf-icon-cloud block md:hidden h-20 bg-center bg-no-repeat"></span>
    <span class="cf-icon-ok w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span>
  </div>
  <span class="md:block w-full truncate">Lagos</span>
  <h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3">Cloudflare</h3>
  <span class="leading-1.3 text-2xl text-green-success">Working</span>
</div>

<div id="cf-host-status" class="cf-error-source relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center">
  <div class="relative mb-10 md:m-0">
    <span class="cf-icon-server block md:hidden h-20 bg-center bg-no-repeat"></span>
    <span class="cf-icon-error w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span>
  </div>
  <span class="md:block w-full truncate">api-demo.fxcm.com</span>
  <h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3">Host</h3>
  <span class="leading-1.3 text-2xl text-red-error">Error</span>
</div>

                </div>
              
            </div>
        </div>

        <div class="w-240 lg:w-full mx-auto mb-8 lg:px-8">
            <div class="clearfix">
                <div class="w-1/2 md:w-full float-left pr-6 md:pb-10 md:pr-0 leading-relaxed">
                    <h2 class="text-3xl font-normal leading-1.3 mb-4">What happened?</h2>
                    <p>There is an unknown connection issue between Cloudflare and the origin web server. As a result, the web page can not be displayed.</p>
                </div>
              
                <div class="w-1/2 md:w-full float-left leading-relaxed">
                    <h2 class="text-3xl font-normal leading-1.3 mb-4">What can I do?</h2>
                          <h3 class="text-15 font-semibold mb-2">If you are a visitor of this website:</h3>
      <p class="mb-6">Please try again in a few minutes.</p>

      <h3 class="text-15 font-semibold mb-2">If you are the owner of this website:</h3>
      <p><span>There is an issue between Cloudflare's cache and your origin web server. Cloudflare monitors for these errors and automatically investigates the cause. To help support the investigation, you can pull the corresponding error log from your web server and submit it our support team.  Please include the Ray ID (which is at the bottom of this error page).</span> <a rel="noopener noreferrer" href="https://support.cloudflare.com/hc/en-us/articles/200171936-Error-520">Additional troubleshooting resources</a>.</p>
                </div>
            </div>
              
        </div>

        <div class="cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center sm:text-left border-solid border-0 border-t border-gray-300">
  <p class="text-13">
    <span class="cf-footer-item sm:block sm:mb-1">Cloudflare Ray ID: <strong class="font-semibold">630fe1427fd8c4ec</strong></span>
    <span class="cf-footer-separator sm:hidden">&bull;</span>
    <span class="cf-footer-item sm:block sm:mb-1"><span>Your IP</span>: 105.112.38.242</span>
    <span class="cf-footer-separator sm:hidden">&bull;</span>
    <span class="cf-footer-item sm:block sm:mb-1"><span>Performance &amp; security by</span> <a rel="noopener noreferrer" href="https://www.cloudflare.com/5xx-error-landing" id="brand_link" target="_blank">Cloudflare</a></span>
    
  </p>
</div><!-- /.error-footer -->


    </div>
</div>
</body>
</html>

"
|ERROR|2021-03-16 19:00:11,396|Call of update raised an error:
|ERROR|2021-03-16 19:00:11,396|<class 'UnboundLocalError'>
|ERROR|2021-03-16 19:00:11,397|local variable '_close' referenced before assignment
|ERROR|2021-03-16 19:00:12,612|Call of update raised an error:
|ERROR|2021-03-16 19:00:12,613|<class 'UnboundLocalError'>
|ERROR|2021-03-16 19:00:12,613|local variable '_close' referenced before assignment
|ERROR|2021-03-16 19:00:13,489|Call of update raised an error:
|ERROR|2021-03-16 19:00:13,492|<class 'UnboundLocalError'>
|ERROR|2021-03-16 19:00:13,492|local variable '_close' referenced before assignment
|ERROR|2021-03-16 19:00:14,778|Call of update raised an error:
|ERROR|2021-03-16 19:00:14,779|<class 'UnboundLocalError'>
|ERROR|2021-03-16 19:00:14,779|local variable '_close' referenced before assignment
|ERROR|2021-03-16 19:00:15,802|Call of update raised an error:
|ERROR|2021-03-16 19:00:15,805|<class 'UnboundLocalError'>
|ERROR|2021-03-16 19:00:15,805|local variable '_close' referenced before assignment
|ERROR|2021-03-16 19:00:15,880|Call of update raised an error:
|ERROR|2021-03-16 19:00:15,882|<class 'UnboundLocalError'>
|ERROR|2021-03-16 19:00:15,883|local variable '_close' referenced before assignment
|ERROR|2021-03-16 19:00:15,922|Call of update raised an error:
|ERROR|2021-03-16 19:00:15,922|<class 'UnboundLocalError'>
|ERROR|2021-03-16 19:00:15,923|local variable '_close' referenced before assignment
|ERROR|2021-03-16 19:00:17,011|Call of update raised an error:
|ERROR|2021-03-16 19:00:17,012|<class 'UnboundLocalError'>
|ERROR|2021-03-16 19:00:17,012|local variable '_close' referenced before assignment
|ERROR|2021-03-16 19:00:18,418|Call of update raised an error:
|ERROR|2021-03-16 19:00:18,419|<class 'UnboundLocalError'>
|ERROR|2021-03-16 19:00:18,419|local variable '_close' referenced before assignment
|ERROR|2021-03-16 19:00:19,136|FXCM reject req candles/2/m1 with status 520 and msg <!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en-US"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en-US"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en-US"> <!--<![endif]-->
<head>
<meta http-equiv="refresh" content="0">

<title>api-demo.fxcm.com | 520: Web server is returning an unknown error</title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/main.css" type="text/css" media="screen,projection" />


</head>
<body>
<div id="cf-wrapper">

    

    <div id="cf-error-details" class="p-0">
        <header class="mx-auto pt-10 lg:pt-6 lg:px-8 w-240 lg:w-full mb-8">
            <h1 class="inline-block sm:block sm:mb-2 font-light text-60 lg:text-4xl text-black-dark leading-tight mr-2">
              
              <span class="cf-error-type">Error</span>
              <span class="cf-error-code">520</span>
            </h1>
            <span class="inline-block sm:block font-mono text-15 lg:text-sm lg:leading-relaxed">Ray ID: 630fe1762ff5c500 &bull;</span>
            <span class="inline-block sm:block font-mono text-15 lg:text-sm lg:leading-relaxed">2021-03-16 18:00:23 UTC</span>
            <h2 class="text-gray-600 leading-1.3 text-3xl font-light">Web server is returning an unknown error</h2>
        </header>
        
        <div class="my-8 bg-gradient-gray">
            <div class="w-240 lg:w-full mx-auto">
                <div class="clearfix md:px-8">
                  
<div id="cf-browser-status" class=" relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center">
  <div class="relative mb-10 md:m-0">
    <span class="cf-icon-browser block md:hidden h-20 bg-center bg-no-repeat"></span>
    <span class="cf-icon-ok w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span>
  </div>
  <span class="md:block w-full truncate">You</span>
  <h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3">Browser</h3>
  <span class="leading-1.3 text-2xl text-green-success">Working</span>
</div>

<div id="cf-cloudflare-status" class=" relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center">
  <div class="relative mb-10 md:m-0">
    <span class="cf-icon-cloud block md:hidden h-20 bg-center bg-no-repeat"></span>
    <span class="cf-icon-ok w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span>
  </div>
  <span class="md:block w-full truncate">Lagos</span>
  <h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3">Cloudflare</h3>
  <span class="leading-1.3 text-2xl text-green-success">Working</span>
</div>

<div id="cf-host-status" class="cf-error-source relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center">
  <div class="relative mb-10 md:m-0">
    <span class="cf-icon-server block md:hidden h-20 bg-center bg-no-repeat"></span>
    <span class="cf-icon-error w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span>
  </div>
  <span class="md:block w-full truncate">api-demo.fxcm.com</span>
  <h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3">Host</h3>
  <span class="leading-1.3 text-2xl text-red-error">Error</span>
</div>

                </div>
              
            </div>
        </div>

        <div class="w-240 lg:w-full mx-auto mb-8 lg:px-8">
            <div class="clearfix">
                <div class="w-1/2 md:w-full float-left pr-6 md:pb-10 md:pr-0 leading-relaxed">
                    <h2 class="text-3xl font-normal leading-1.3 mb-4">What happened?</h2>
                    <p>There is an unknown connection issue between Cloudflare and the origin web server. As a result, the web page can not be displayed.</p>
                </div>
              
                <div class="w-1/2 md:w-full float-left leading-relaxed">
                    <h2 class="text-3xl font-normal leading-1.3 mb-4">What can I do?</h2>
                          <h3 class="text-15 font-semibold mb-2">If you are a visitor of this website:</h3>
      <p class="mb-6">Please try again in a few minutes.</p>

      <h3 class="text-15 font-semibold mb-2">If you are the owner of this website:</h3>
      <p><span>There is an issue between Cloudflare's cache and your origin web server. Cloudflare monitors for these errors and automatically investigates the cause. To help support the investigation, you can pull the corresponding error log from your web server and submit it our support team.  Please include the Ray ID (which is at the bottom of this error page).</span> <a rel="noopener noreferrer" href="https://support.cloudflare.com/hc/en-us/articles/200171936-Error-520">Additional troubleshooting resources</a>.</p>
                </div>
            </div>
              
        </div>

        <div class="cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center sm:text-left border-solid border-0 border-t border-gray-300">
  <p class="text-13">
    <span class="cf-footer-item sm:block sm:mb-1">Cloudflare Ray ID: <strong class="font-semibold">630fe1762ff5c500</strong></span>
    <span class="cf-footer-separator sm:hidden">&bull;</span>
    <span class="cf-footer-item sm:block sm:mb-1"><span>Your IP</span>: 105.112.38.242</span>
    <span class="cf-footer-separator sm:hidden">&bull;</span>
    <span class="cf-footer-item sm:block sm:mb-1"><span>Performance &amp; security by</span> <a rel="noopener noreferrer" href="https://www.cloudflare.com/5xx-error-landing" id="brand_link" target="_blank">Cloudflare</a></span>
    
  </p>
</div><!-- /.error-footer -->


    </div>
</div>
</body>
</html>

.
|ERROR|2021-03-16 19:00:19,137|Call of update raised an error:
|ERROR|2021-03-16 19:00:19,138|<class 'fxcmpy.fxcmpy.ServerError'>
|ERROR|2021-03-16 19:00:19,139|Request returns status code 520 and message "<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en-US"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en-US"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en-US"> <!--<![endif]-->
<head>
<meta http-equiv="refresh" content="0">

<title>api-demo.fxcm.com | 520: Web server is returning an unknown error</title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/main.css" type="text/css" media="screen,projection" />


</head>
<body>
<div id="cf-wrapper">

    

    <div id="cf-error-details" class="p-0">
        <header class="mx-auto pt-10 lg:pt-6 lg:px-8 w-240 lg:w-full mb-8">
            <h1 class="inline-block sm:block sm:mb-2 font-light text-60 lg:text-4xl text-black-dark leading-tight mr-2">
              
              <span class="cf-error-type">Error</span>
              <span class="cf-error-code">520</span>
            </h1>
            <span class="inline-block sm:block font-mono text-15 lg:text-sm lg:leading-relaxed">Ray ID: 630fe1762ff5c500 &bull;</span>
            <span class="inline-block sm:block font-mono text-15 lg:text-sm lg:leading-relaxed">2021-03-16 18:00:23 UTC</span>
            <h2 class="text-gray-600 leading-1.3 text-3xl font-light">Web server is returning an unknown error</h2>
        </header>
        
        <div class="my-8 bg-gradient-gray">
            <div class="w-240 lg:w-full mx-auto">
                <div class="clearfix md:px-8">
                  
<div id="cf-browser-status" class=" relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center">
  <div class="relative mb-10 md:m-0">
    <span class="cf-icon-browser block md:hidden h-20 bg-center bg-no-repeat"></span>
    <span class="cf-icon-ok w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span>
  </div>
  <span class="md:block w-full truncate">You</span>
  <h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3">Browser</h3>
  <span class="leading-1.3 text-2xl text-green-success">Working</span>
</div>

<div id="cf-cloudflare-status" class=" relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center">
  <div class="relative mb-10 md:m-0">
    <span class="cf-icon-cloud block md:hidden h-20 bg-center bg-no-repeat"></span>
    <span class="cf-icon-ok w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span>
  </div>
  <span class="md:block w-full truncate">Lagos</span>
  <h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3">Cloudflare</h3>
  <span class="leading-1.3 text-2xl text-green-success">Working</span>
</div>

<div id="cf-host-status" class="cf-error-source relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center">
  <div class="relative mb-10 md:m-0">
    <span class="cf-icon-server block md:hidden h-20 bg-center bg-no-repeat"></span>
    <span class="cf-icon-error w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span>
  </div>
  <span class="md:block w-full truncate">api-demo.fxcm.com</span>
  <h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3">Host</h3>
  <span class="leading-1.3 text-2xl text-red-error">Error</span>
</div>

                </div>
              
            </div>
        </div>

        <div class="w-240 lg:w-full mx-auto mb-8 lg:px-8">
            <div class="clearfix">
                <div class="w-1/2 md:w-full float-left pr-6 md:pb-10 md:pr-0 leading-relaxed">
                    <h2 class="text-3xl font-normal leading-1.3 mb-4">What happened?</h2>
                    <p>There is an unknown connection issue between Cloudflare and the origin web server. As a result, the web page can not be displayed.</p>
                </div>
              
                <div class="w-1/2 md:w-full float-left leading-relaxed">
                    <h2 class="text-3xl font-normal leading-1.3 mb-4">What can I do?</h2>
                          <h3 class="text-15 font-semibold mb-2">If you are a visitor of this website:</h3>
      <p class="mb-6">Please try again in a few minutes.</p>

      <h3 class="text-15 font-semibold mb-2">If you are the owner of this website:</h3>
      <p><span>There is an issue between Cloudflare's cache and your origin web server. Cloudflare monitors for these errors and automatically investigates the cause. To help support the investigation, you can pull the corresponding error log from your web server and submit it our support team.  Please include the Ray ID (which is at the bottom of this error page).</span> <a rel="noopener noreferrer" href="https://support.cloudflare.com/hc/en-us/articles/200171936-Error-520">Additional troubleshooting resources</a>.</p>
                </div>
            </div>
              
        </div>

        <div class="cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center sm:text-left border-solid border-0 border-t border-gray-300">
  <p class="text-13">
    <span class="cf-footer-item sm:block sm:mb-1">Cloudflare Ray ID: <strong class="font-semibold">630fe1762ff5c500</strong></span>
    <span class="cf-footer-separator sm:hidden">&bull;</span>
    <span class="cf-footer-item sm:block sm:mb-1"><span>Your IP</span>: 105.112.38.242</span>
    <span class="cf-footer-separator sm:hidden">&bull;</span>
    <span class="cf-footer-item sm:block sm:mb-1"><span>Performance &amp; security by</span> <a rel="noopener noreferrer" href="https://www.cloudflare.com/5xx-error-landing" id="brand_link" target="_blank">Cloudflare</a></span>
    
  </p>
</div><!-- /.error-footer -->


    </div>
</div>
</body>
</html>

"
|ERROR|2021-03-16 19:00:19,320|Call of update raised an error:
|ERROR|2021-03-16 19:00:19,525|<class 'UnboundLocalError'>
|ERROR|2021-03-16 19:00:19,526|local variable '_close' referenced before assignment
|ERROR|2021-03-16 19:00:19,425|Call of update raised an error:
|ERROR|2021-03-16 19:00:19,530|<class 'UnboundLocalError'>
|ERROR|2021-03-16 19:00:19,530|local variable '_close' referenced before assignment
|ERROR|2021-03-16 19:00:19,427|Call of update raised an error:
|ERROR|2021-03-16 19:00:19,531|<class 'UnboundLocalError'>
|ERROR|2021-03-16 19:00:19,531|local variable '_close' referenced before assignment
|ERROR|2021-03-16 19:00:20,083|Call of update raised an error:
|ERROR|2021-03-16 19:00:20,083|<class 'UnboundLocalError'>
|ERROR|2021-03-16 19:00:20,093|local variable '_close' referenced before assignment
|ERROR|2021-03-16 19:00:20,098|Call of update raised an error:
|ERROR|2021-03-16 19:00:20,118|<class 'UnboundLocalError'>
|ERROR|2021-03-16 19:00:20,119|local variable '_close' referenced before assignment
|ERROR|2021-03-16 19:00:20,213|Call of update raised an error:
|ERROR|2021-03-16 19:00:20,214|<class 'UnboundLocalError'>
|ERROR|2021-03-16 19:00:20,215|local variable '_close' referenced before assignment
|ERROR|2021-03-16 19:00:20,688|Call of update raised an error:
|ERROR|2021-03-16 19:00:20,689|<class 'UnboundLocalError'>
|ERROR|2021-03-16 19:00:20,689|local variable '_close' referenced before assignment
|ERROR|2021-03-16 19:00:20,917|Call of update raised an error:
|ERROR|2021-03-16 19:00:20,918|<class 'UnboundLocalError'>
|ERROR|2021-03-16 19:00:20,918|local variable '_close' referenced before assignment
|ERROR|2021-03-16 19:00:21,452|Call of update raised an error:
|ERROR|2021-03-16 19:00:21,498|<class 'UnboundLocalError'>
|ERROR|2021-03-16 19:00:21,498|local variable '_close' referenced before assignment
|ERROR|2021-03-16 19:00:23,509|Call of update raised an error:
|ERROR|2021-03-16 19:00:23,509|<class 'UnboundLocalError'>
|ERROR|2021-03-16 19:00:23,510|local variable '_close' referenced before assignment
|ERROR|2021-03-16 19:00:23,579|Call of update raised an error:
|ERROR|2021-03-16 19:00:23,580|<class 'UnboundLocalError'>
|ERROR|2021-03-16 19:00:23,580|local variable '_close' referenced before assignment
|ERROR|2021-03-16 19:00:37,688|Call of update raised an error:
|ERROR|2021-03-16 19:00:37,688|<class 'UnboundLocalError'>
|ERROR|2021-03-16 19:00:37,689|local variable '_close' referenced before assignment
|ERROR|2021-03-16 19:00:38,274|Call of update raised an error:
|ERROR|2021-03-16 19:00:38,275|<class 'UnboundLocalError'>
|ERROR|2021-03-16 19:00:38,275|local variable '_close' referenced before assignment
|ERROR|2021-03-16 19:00:39,405|Call of update raised an error:
|ERROR|2021-03-16 19:00:39,406|<class 'UnboundLocalError'>
|ERROR|2021-03-16 19:00:39,407|local variable '_close' referenced before assignment
|ERROR|2021-03-16 19:00:40,182|Call of update raised an error:
|ERROR|2021-03-16 19:00:40,222|<class 'UnboundLocalError'>
|ERROR|2021-03-16 19:00:40,222|local variable '_close' referenced before assignment
|ERROR|2021-03-16 19:00:40,219|Call of update raised an error:
|ERROR|2021-03-16 19:00:40,225|<class 'UnboundLocalError'>
|ERROR|2021-03-16 19:00:40,225|local variable '_close' referenced before assignment
|ERROR|2021-03-16 19:00:44,231|Call of update raised an error:
|ERROR|2021-03-16 19:00:44,232|<class 'UnboundLocalError'>
|ERROR|2021-03-16 19:00:44,233|local variable '_close' referenced before assignment
|ERROR|2021-03-16 19:00:47,674|Call of update raised an error:
|ERROR|2021-03-16 19:00:47,689|<class 'UnboundLocalError'>
|ERROR|2021-03-16 19:00:47,689|local variable '_close' referenced before assignment
|ERROR|2021-03-16 19:00:51,166|Call of update raised an error:
|ERROR|2021-03-16 19:00:51,166|<class 'UnboundLocalError'>
|ERROR|2021-03-16 19:00:51,167|local variable '_close' referenced before assignment
|ERROR|2021-03-16 19:00:51,230|Call of update raised an error:
|ERROR|2021-03-16 19:00:51,230|<class 'UnboundLocalError'>
|ERROR|2021-03-16 19:00:51,231|local variable '_close' referenced before assignment
|INFO|2021-03-16 19:10:07,141|C:\Users\Administrator\Documents\Github\OatFX\OatFX\shared.py changed, reloading.
|ERROR|2021-03-17 10:50:56,631|Call of update raised an error:
|ERROR|2021-03-17 10:50:56,668|<class 'KeyError'>
|ERROR|2021-03-17 10:50:56,668|'Bid'
|ERROR|2021-03-17 10:50:58,282|Call of update raised an error:
|ERROR|2021-03-17 10:50:58,283|<class 'KeyError'>
|ERROR|2021-03-17 10:50:58,283|'Bid'
|ERROR|2021-03-17 10:50:59,499|Call of update raised an error:
|ERROR|2021-03-17 10:50:59,500|<class 'KeyError'>
|ERROR|2021-03-17 10:50:59,501|'Bid'
|ERROR|2021-03-17 10:51:01,318|Call of update raised an error:
|ERROR|2021-03-17 10:51:01,319|<class 'KeyError'>
|ERROR|2021-03-17 10:51:01,319|'Bid'
|ERROR|2021-03-17 10:51:02,133|Call of update raised an error:
|ERROR|2021-03-17 10:51:02,134|<class 'KeyError'>
|ERROR|2021-03-17 10:51:02,135|'Bid'
|ERROR|2021-03-17 10:51:02,932|Call of update raised an error:
|ERROR|2021-03-17 10:51:02,933|<class 'KeyError'>
|ERROR|2021-03-17 10:51:02,933|'Bid'
|ERROR|2021-03-17 10:51:05,173|Call of update raised an error:
|ERROR|2021-03-17 10:51:05,173|<class 'KeyError'>
|ERROR|2021-03-17 10:51:05,184|'Bid'
|ERROR|2021-03-17 10:51:05,403|Call of update raised an error:
|ERROR|2021-03-17 10:51:05,404|<class 'KeyError'>
|ERROR|2021-03-17 10:51:05,404|'Bid'
|ERROR|2021-03-17 10:51:06,178|Call of update raised an error:
|ERROR|2021-03-17 10:51:06,179|<class 'KeyError'>
|ERROR|2021-03-17 10:51:06,179|'Bid'
|ERROR|2021-03-17 10:51:09,430|Call of update raised an error:
|ERROR|2021-03-17 10:51:09,431|<class 'KeyError'>
|ERROR|2021-03-17 10:51:09,431|'Bid'
|ERROR|2021-03-17 10:51:09,518|Call of update raised an error:
|ERROR|2021-03-17 10:51:09,520|<class 'KeyError'>
|ERROR|2021-03-17 10:51:09,522|'Bid'
|ERROR|2021-03-17 10:51:30,535|Socket returns unknown error.
|ERROR|2021-03-17 10:51:30,536|Connection aborted, failed to reconnect
|ERROR|2021-03-17 10:51:30,536|Call of update raised an error:
|ERROR|2021-03-17 10:51:30,536|<class 'OSError'>
|ERROR|2021-03-17 10:51:30,537|Connection aborted, failed to reconnect
|ERROR|2021-03-17 10:51:30,539|Socket returns unknown error.
|ERROR|2021-03-17 10:51:30,540|Connection aborted, failed to reconnect
|ERROR|2021-03-17 10:51:30,541|Call of update raised an error:
|ERROR|2021-03-17 10:51:30,541|<class 'OSError'>
|ERROR|2021-03-17 10:51:30,542|Connection aborted, failed to reconnect
|ERROR|2021-03-17 10:51:33,979|Server reports an error: {'executed': False, 'error': 'Unauthorized'}.
|ERROR|2021-03-17 10:51:33,980|URL: https://api-demo.fxcm.com:443/candles/2/m1?num=1
|ERROR|2021-03-17 10:51:33,980|Headers: {'User-Agent': 'request', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Authorization': 'Bearer KF2_1urEQIXCm9knAUqA428f4f0130d439c3d02922e4a5d4640a783830fb', 'Content-Type': 'application/x-www-form-urlencoded'}
|ERROR|2021-03-17 10:51:33,981|Params: {'num': 1}
|ERROR|2021-03-17 10:51:33,981|Bearer token: Bearer KF2_1urEQIXCm9knAUqA428f4f0130d439c3d02922e4a5d4640a783830fb
|ERROR|2021-03-17 10:51:33,981|Connection status: unset
|ERROR|2021-03-17 10:51:33,982|Can not parse server answer to json object: {"response":{"executed":false,"error":"Unauthorized"},"instrument_id":0,"period_id":0,"candles":[]}.
|ERROR|2021-03-17 10:52:47,227|Call of update raised an error:
|ERROR|2021-03-17 10:52:47,228|<class 'KeyError'>
|ERROR|2021-03-17 10:52:47,228|'Bid'
|ERROR|2021-03-17 10:52:48,288|Call of update raised an error:
|ERROR|2021-03-17 10:52:48,290|<class 'KeyError'>
|ERROR|2021-03-17 10:52:48,290|'Bid'
|ERROR|2021-03-17 10:52:49,723|Call of update raised an error:
|ERROR|2021-03-17 10:52:49,724|<class 'KeyError'>
|ERROR|2021-03-17 10:52:49,724|'Bid'
|ERROR|2021-03-17 10:52:50,314|Call of update raised an error:
|ERROR|2021-03-17 10:52:50,318|<class 'KeyError'>
|ERROR|2021-03-17 10:52:50,320|'Bid'
|ERROR|2021-03-17 10:52:51,963|Call of update raised an error:
|ERROR|2021-03-17 10:52:51,968|<class 'KeyError'>
|ERROR|2021-03-17 10:52:51,969|'Bid'
|ERROR|2021-03-17 10:52:57,596|Call of update raised an error:
|ERROR|2021-03-17 10:52:57,597|<class 'KeyError'>
|ERROR|2021-03-17 10:52:57,597|'Bid'
|ERROR|2021-03-17 10:52:57,986|Call of update raised an error:
|ERROR|2021-03-17 10:52:57,986|<class 'KeyError'>
|ERROR|2021-03-17 10:52:57,987|'Bid'
|ERROR|2021-03-17 10:52:58,286|Call of update raised an error:
|ERROR|2021-03-17 10:52:58,287|<class 'KeyError'>
|ERROR|2021-03-17 10:52:58,287|'Bid'
|ERROR|2021-03-17 10:53:03,946|Call of update raised an error:
|ERROR|2021-03-17 10:53:03,946|<class 'KeyError'>
|ERROR|2021-03-17 10:53:03,947|'Bid'
|ERROR|2021-03-17 10:53:05,587|Call of update raised an error:
|ERROR|2021-03-17 10:53:05,588|<class 'KeyError'>
|ERROR|2021-03-17 10:53:05,588|'Bid'
|ERROR|2021-03-17 10:53:06,164|Call of update raised an error:
|ERROR|2021-03-17 10:53:06,165|<class 'KeyError'>
|ERROR|2021-03-17 10:53:06,165|'Bid'
|ERROR|2021-03-17 10:53:08,708|Call of update raised an error:
|ERROR|2021-03-17 10:53:08,708|<class 'KeyError'>
|ERROR|2021-03-17 10:53:08,708|'Bid'
|ERROR|2021-03-17 10:53:09,309|Call of update raised an error:
|ERROR|2021-03-17 10:53:09,309|<class 'KeyError'>
|ERROR|2021-03-17 10:53:09,310|'Bid'
|ERROR|2021-03-17 10:53:11,658|Call of update raised an error:
|ERROR|2021-03-17 10:53:11,659|<class 'KeyError'>
|ERROR|2021-03-17 10:53:11,663|'Bid'
|ERROR|2021-03-17 10:53:12,107|Call of update raised an error:
|ERROR|2021-03-17 10:53:12,108|<class 'KeyError'>
|ERROR|2021-03-17 10:53:12,111|'Bid'
|ERROR|2021-03-17 10:53:16,211|Call of update raised an error:
|ERROR|2021-03-17 10:53:16,211|<class 'KeyError'>
|ERROR|2021-03-17 10:53:16,212|'Bid'
|ERROR|2021-03-17 10:53:16,537|Call of update raised an error:
|ERROR|2021-03-17 10:53:16,538|<class 'KeyError'>
|ERROR|2021-03-17 10:53:16,539|'Bid'
|ERROR|2021-03-17 10:53:16,924|Call of update raised an error:
|ERROR|2021-03-17 10:53:16,925|<class 'KeyError'>
|ERROR|2021-03-17 10:53:16,925|'Bid'
|ERROR|2021-03-17 10:53:18,869|Call of update raised an error:
|ERROR|2021-03-17 10:53:18,870|<class 'KeyError'>
|ERROR|2021-03-17 10:53:18,870|'Bid'
|ERROR|2021-03-17 10:53:19,629|Call of update raised an error:
|ERROR|2021-03-17 10:53:19,630|<class 'KeyError'>
|ERROR|2021-03-17 10:53:19,630|'Bid'
|ERROR|2021-03-17 10:53:19,926|Call of update raised an error:
|ERROR|2021-03-17 10:53:19,926|<class 'KeyError'>
|ERROR|2021-03-17 10:53:19,927|'Bid'
|ERROR|2021-03-17 10:53:20,526|Call of update raised an error:
|ERROR|2021-03-17 10:53:20,526|<class 'KeyError'>
|ERROR|2021-03-17 10:53:20,527|'Bid'
|ERROR|2021-03-17 10:53:20,781|Call of update raised an error:
|ERROR|2021-03-17 10:53:20,802|<class 'KeyError'>
|ERROR|2021-03-17 10:53:20,803|'Bid'
|ERROR|2021-03-17 10:53:20,885|Call of update raised an error:
|ERROR|2021-03-17 10:53:20,886|<class 'KeyError'>
|ERROR|2021-03-17 10:53:20,887|'Bid'
|INFO|2021-03-17 10:55:01,203|C:\Users\Administrator\Documents\Github\OatFX\OatFX\shared.py changed, reloading.
|INFO|2021-03-17 11:14:33,410|C:\Users\Administrator\Documents\Github\OatFX\OatFX\shared.py changed, reloading.
|ERROR|2021-03-17 11:21:03,714|Server reports an error: {'executed': False, 'error': 'Unauthorized'}.
|ERROR|2021-03-17 11:21:03,755|URL: https://api-demo.fxcm.com:443/candles/3/m1?num=1
|ERROR|2021-03-17 11:21:03,756|Headers: {'User-Agent': 'request', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Authorization': 'Bearer 8LTuLxjU00ZJid3GAVcu428f4f0130d439c3d02922e4a5d4640a783830fb', 'Content-Type': 'application/x-www-form-urlencoded'}
|ERROR|2021-03-17 11:21:03,756|Params: {'num': 1}
|ERROR|2021-03-17 11:21:03,757|Bearer token: None
|ERROR|2021-03-17 11:21:03,758|Connection status: unset
|ERROR|2021-03-17 11:21:03,758|Socket session id: None
|ERROR|2021-03-17 11:21:03,759|Can not parse server answer to json object: {"response":{"executed":false,"error":"Unauthorized"},"instrument_id":0,"period_id":0,"candles":[]}.
|ERROR|2021-03-17 11:21:03,731|Server reports an error: {'executed': False, 'error': 'Unauthorized'}.
|ERROR|2021-03-17 11:21:03,802|URL: https://api-demo.fxcm.com:443/candles/3/m1?num=1
|ERROR|2021-03-17 11:21:03,802|Headers: {'User-Agent': 'request', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Authorization': 'Bearer 8LTuLxjU00ZJid3GAVcu428f4f0130d439c3d02922e4a5d4640a783830fb', 'Content-Type': 'application/x-www-form-urlencoded'}
|ERROR|2021-03-17 11:21:03,803|Params: {'num': 1}
|ERROR|2021-03-17 11:21:03,803|Bearer token: None
|ERROR|2021-03-17 11:21:03,804|Connection status: unset
|ERROR|2021-03-17 11:21:03,804|Socket session id: None
|ERROR|2021-03-17 11:21:03,804|Can not parse server answer to json object: {"response":{"executed":false,"error":"Unauthorized"},"instrument_id":0,"period_id":0,"candles":[]}.
|ERROR|2021-03-17 11:21:03,742|Server reports an error: {'executed': False, 'error': 'Unauthorized'}.
|ERROR|2021-03-17 11:21:03,885|URL: https://api-demo.fxcm.com:443/candles/3/m1?num=1
|ERROR|2021-03-17 11:21:03,886|Headers: {'User-Agent': 'request', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Authorization': 'Bearer 8LTuLxjU00ZJid3GAVcu428f4f0130d439c3d02922e4a5d4640a783830fb', 'Content-Type': 'application/x-www-form-urlencoded'}
|ERROR|2021-03-17 11:21:03,886|Params: {'num': 1}
|ERROR|2021-03-17 11:21:03,991|Bearer token: None
|ERROR|2021-03-17 11:21:03,991|Connection status: unset
|ERROR|2021-03-17 11:21:03,992|Socket session id: None
|ERROR|2021-03-17 11:21:03,992|Can not parse server answer to json object: {"response":{"executed":false,"error":"Unauthorized"},"instrument_id":0,"period_id":0,"candles":[]}.
|ERROR|2021-03-17 11:21:03,755|Server reports an error: {'executed': False, 'error': 'Unauthorized'}.
|ERROR|2021-03-17 11:21:04,237|URL: https://api-demo.fxcm.com:443/candles/3/m1?num=1
|ERROR|2021-03-17 11:21:04,238|Headers: {'User-Agent': 'request', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Authorization': 'Bearer 8LTuLxjU00ZJid3GAVcu428f4f0130d439c3d02922e4a5d4640a783830fb', 'Content-Type': 'application/x-www-form-urlencoded'}
|ERROR|2021-03-17 11:21:04,238|Params: {'num': 1}
|ERROR|2021-03-17 11:21:04,238|Bearer token: None
|ERROR|2021-03-17 11:21:04,239|Connection status: unset
|ERROR|2021-03-17 11:21:04,239|Socket session id: None
|ERROR|2021-03-17 11:21:04,239|Can not parse server answer to json object: {"response":{"executed":false,"error":"Unauthorized"},"instrument_id":0,"period_id":0,"candles":[]}.
|ERROR|2021-03-17 11:21:04,090|Server reports an error: {'executed': False, 'error': 'Unauthorized'}.
|ERROR|2021-03-17 11:21:04,378|URL: https://api-demo.fxcm.com:443/candles/3/m1?num=1
|ERROR|2021-03-17 11:21:04,379|Headers: {'User-Agent': 'request', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Authorization': 'Bearer 8LTuLxjU00ZJid3GAVcu428f4f0130d439c3d02922e4a5d4640a783830fb', 'Content-Type': 'application/x-www-form-urlencoded'}
|ERROR|2021-03-17 11:21:04,380|Params: {'num': 1}
|ERROR|2021-03-17 11:21:04,380|Bearer token: None
|ERROR|2021-03-17 11:21:04,384|Connection status: unset
|ERROR|2021-03-17 11:21:04,384|Socket session id: None
|ERROR|2021-03-17 11:21:04,385|Can not parse server answer to json object: {"response":{"executed":false,"error":"Unauthorized"},"instrument_id":0,"period_id":0,"candles":[]}.
|ERROR|2021-03-17 11:21:04,163|Server reports an error: {'executed': False, 'error': 'Unauthorized'}.
|ERROR|2021-03-17 11:21:04,360|Server reports an error: {'executed': False, 'error': 'Unauthorized'}.
|ERROR|2021-03-17 11:21:04,449|URL: https://api-demo.fxcm.com:443/candles/3/m1?num=1
|ERROR|2021-03-17 11:21:04,450|URL: https://api-demo.fxcm.com:443/candles/3/m1?num=1
|ERROR|2021-03-17 11:21:04,451|Headers: {'User-Agent': 'request', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Authorization': 'Bearer 8LTuLxjU00ZJid3GAVcu428f4f0130d439c3d02922e4a5d4640a783830fb', 'Content-Type': 'application/x-www-form-urlencoded'}
|ERROR|2021-03-17 11:21:04,452|Headers: {'User-Agent': 'request', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Authorization': 'Bearer 8LTuLxjU00ZJid3GAVcu428f4f0130d439c3d02922e4a5d4640a783830fb', 'Content-Type': 'application/x-www-form-urlencoded'}
|ERROR|2021-03-17 11:21:04,452|Params: {'num': 1}
|ERROR|2021-03-17 11:21:04,453|Params: {'num': 1}
|ERROR|2021-03-17 11:21:04,454|Bearer token: None
|ERROR|2021-03-17 11:21:04,454|Bearer token: None
|ERROR|2021-03-17 11:21:04,455|Connection status: unset
|ERROR|2021-03-17 11:21:04,455|Connection status: unset
|ERROR|2021-03-17 11:21:04,457|Socket session id: None
|ERROR|2021-03-17 11:21:04,456|Socket session id: None
|ERROR|2021-03-17 11:21:04,457|Can not parse server answer to json object: {"response":{"executed":false,"error":"Unauthorized"},"instrument_id":0,"period_id":0,"candles":[]}.
|ERROR|2021-03-17 11:21:04,458|Can not parse server answer to json object: {"response":{"executed":false,"error":"Unauthorized"},"instrument_id":0,"period_id":0,"candles":[]}.
|ERROR|2021-03-17 11:21:05,007|Server reports an error: {'executed': False, 'error': 'Unauthorized'}.
|ERROR|2021-03-17 11:21:05,008|URL: https://api-demo.fxcm.com:443/candles/3/m1?num=1
|ERROR|2021-03-17 11:21:05,008|Headers: {'User-Agent': 'request', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Authorization': 'Bearer 8LTuLxjU00ZJid3GAVcu428f4f0130d439c3d02922e4a5d4640a783830fb', 'Content-Type': 'application/x-www-form-urlencoded'}
|ERROR|2021-03-17 11:21:05,009|Params: {'num': 1}
|ERROR|2021-03-17 11:21:05,009|Bearer token: None
|ERROR|2021-03-17 11:21:05,009|Connection status: unset
|ERROR|2021-03-17 11:21:05,010|Socket session id: None
|ERROR|2021-03-17 11:21:05,010|Can not parse server answer to json object: {"response":{"executed":false,"error":"Unauthorized"},"instrument_id":0,"period_id":0,"candles":[]}.
|INFO|2021-03-17 18:33:29,763|C:\Users\Administrator\Documents\Github\OatFX\OatFX\shared.py changed, reloading.
|INFO|2021-03-17 18:44:14,026|C:\Users\Administrator\Documents\Github\OatFX\OatFX\shared.py changed, reloading.
|INFO|2021-03-17 18:48:58,495|C:\Users\Administrator\Documents\Github\OatFX\OatFX\shared.py changed, reloading.
|INFO|2021-03-17 19:13:49,607|C:\Users\Administrator\Documents\Github\OatFX\OatFX\shared.py changed, reloading.
|INFO|2021-03-17 19:16:24,837|C:\Users\Administrator\Documents\Github\OatFX\OatFX\shared.py changed, reloading.
|INFO|2021-03-19 18:40:02,237|C:\Users\Administrator\Documents\Github\OatFX\OatFX\views.py changed, reloading.
